### ISSUE TITLE
Got redbox with Chrome Debugging when run the Simple example.

### ISSUE THREAD

**Issue by jacobbubu** [ProjectSeptemberInc/gl-react-native#1]
![screen shot 2015-08-31 at 11 20 29 am](https://cloud.githubusercontent.com/assets/1164378/9571595/7cde650e-4fd2-11e5-8333-02b55dfa656a.png)

**Comment by gre** [comment]
Try to reinstall `gl-react-native` and this should be fixed by https://github.com/ProjectSeptemberInc/gl-react-core/commit/3a701956e343f2087cd737acd8f20b759752ad9e

**Comment by jacobbubu** [comment]
It worked, thanks you! 

But there is a warning appearing.
![screen shot 2015-08-31 at 5 09 52 pm](https://cloud.githubusercontent.com/assets/1164378/9575546/2e699462-5003-11e5-84cd-3b6fdf7ab3b7.png)

**Comment by gre** [comment]
yeah this warning is I think only coming from this Simple/ example (not the library), will eventually fix it, thanks.
