### ISSUE TITLE
Supports for Animated objects

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react-native#10]
We have proven in [this example using react-motion](http://projectseptemberinc.github.io/gl-react/Examples/SpringCursor/) that _gl-react_ can interoperate with React animation libraries and in the continuation of a "descriptive" expressivity.

Now, in **react-native** context, there is Animated ([docs](https://facebook.github.io/react-native/docs/animations.html) / [source code](https://github.com/facebook/react-native/blob/master/Libraries/Animated/Animated.js)).
I see nothing preventing us for being able to **support this for values passed in `uniforms`.**

As an use-case example: awesome things that solves Animated (like user interruptibility / UI driven like responsive to dragging) could be used with glsl-transitions effects:

![out](https://cloud.githubusercontent.com/assets/211411/9990092/83116132-605e-11e5-8121-a6eabfacb295.gif)
## Code Usage Example

For instance, I should be able to do:

``` js
// example adapted from the React Animation documentation
class Playground extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      animatedValue: new Animated.Value(0)
    };
  }
  render() {
    return (
      <GL.View
        shader={shaders.myEffect2}
        width={200}
        height={100}
        uniforms={{
          value: this.state.animatedValue
        }} />
    );
  }
  componentDidMount() {
    this.state.animatedValue.setValue(1.5);
    Animated.spring(this.state.animatedValue, { toValue: 0.8, friction: 1 }).start();
  }
}
```

Another and more probable use-case is using with a pre-defined GL Component, like [**Blur**](http://projectseptemberinc.github.io/gl-react/Examples/Blur/).
And I should just be able to do:

``` html
<Blur factor={this.state.animatedValue} width={w} height={h}>
  <Something/>
</Blur>
```
## Implementation

**We can implement shader uniform animations in a very efficient way in the Objective-C / OpenGL side.**
Now we can't just use `Animated.createAnimatedComponent` for this because it is specific to animate `style`. Also, in our implementation `uniforms` props DOES NOT directly map to the final component props, in fact `<GL.View/>` is just an intermediary way (DSL) to express a tree of effects and gets transformed to a single [_"GLCanvas"_](https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/RNGL/GLCanvas.h) (`GLKView` in case of iOS).

**A tree of `GL.View` gets consumed and results of a single `data` that contains everything the OpenGL implementation needs to render the effects pipeline.**

For example, see this example (left shows the usage part, right shows the resulting `data` props that represents the usage tree):

<img width="943" alt="screen shot 2015-09-21 at 11 43 43" src="https://cloud.githubusercontent.com/assets/211411/9989106/26c2b8fc-6056-11e5-8f36-9aba633989b9.png">
# Help Wanted on this:

Right now, if we try to use `Animated.Value` as uniforms props, we are going to have this `data` filled with `Animated.Value`s.

So it sounds like we just need a way to **resolve** all `Animated.Value` objects in that object tree. I don't know yet the Animated specifics to implement a Animated Component from scratch and do this resolving:
- Is there a React utility to resolve a object tree filled with some `Animated.Value` at a given time?
- What do we need to do at the component level? (start/stop? render loop? `setNativeProps` for the props that gets animated?)

Thanks

**Comment by gre** [comment]
cc @sahrens @vjeux : any thoughts?

**Comment by vjeux** [comment]
Sorry I don't have the time to look into it :(

**Comment by gre** [comment]
@vjeux no worries. this is still some raw thoughts here, I need to give a try I guess ;)

Do you know if important changes in Animated framework is planned, like if it is planned to implement the animation more efficiently on Obj-C side? I guess if it's planned, I should wait this to come.

**Comment by vjeux** [comment]
> like if it is planned to implement the animation more efficiently on Obj-C side

This is something that needs to be done. But no one is working on it right now.

**Comment by gre** [comment]
`gl-react` 2.1.1 now supports Animated object in uniforms. This is explained in the [release notes](https://github.com/ProjectSeptemberInc/gl-react/releases/tag/v2.1.1),

see also https://github.com/ProjectSeptemberInc/gl-react/blob/master/src/AnimatedData.js , it's a bit hacky as I needed to embed part of the Animated library in (the Animated and AnimatedWithChildren classes) but eventually we should have Animated as a standalone lib (I hope!), at least this works with duck-typing (on `obj.__getValue`).
This should also work for the web version of gl-react (which is gl-react-dom) as soon as we have a compatible Animated version.
