### ISSUE TITLE
Can't run in IOS (Using cocoapods)

### ISSUE THREAD

**Issue by dcworldwide** [ProjectSeptemberInc/gl-react-native#101]
I have the following startup error on IOS.

![simulator screen shot 31 jul 2016 15 28 03](https://cloud.githubusercontent.com/assets/4898751/17274750/8342947e-5733-11e6-87a2-26bb9e7c93cb.png)

I'm running the latest versions of GL react and GL react native. 

I've installed the pod via:

```
cd ios
pod install 
Changed Podfile to:

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'imageGlShaders' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for imageGlShaders
  #pod 'RNGL', :path => '../node_modules/gl-react-native'

  target 'imageGlShadersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod install 

From project root, run react-native run-ios.

```

This is my first time using RN with IOS. Is this a bug or am I doing something wrong? Thanks

**Comment by gre** [comment]
The library works with cocoapods. We use it that way. The error indicates the library is not properly linked and not available on the objc side ios build.

> `#pod 'RNGL', :path => '../node_modules/gl-react-native'`

Why is this part commented?

**Comment by dcworldwide** [comment]
OK thanks. Looks like a silly error. Will retest in morning.

**Comment by dcworldwide** [comment]
Ok, issue was that I need to set project deployment target to IOS version 8 (as per RNGL pod spec). I can install the RNGL pod successfully.

The issue I now have is figuring out how to run it. Do I run react-native run-ios or do I run the xcworkspace from xcode? I've tried either option but they have give build errors. Could someone please help me understand what I'm doing wrong?

**Comment by dcworldwide** [comment]
Going to try trashing my cocoapods repo and trying again.

**Comment by dcworldwide** [comment]
Happy to close it because as an ios noob I'm probably doing something silly. If someone could please share an example podfile however, that would really help those like myself get started with rn and ios.
