### ISSUE TITLE
Nested Surfaces

### ISSUE THREAD

**Issue by sscaff1** [ProjectSeptemberInc/gl-react-native#105]
I'm not sure if this possible. I currently have a component that resizes, pans, and rotates a child (based on a wrapping animated view) . It also animates the child back to the center of the containing view if you try to create whitespace behind the view (similar to instagram, twitter or facebook). 

https://github.com/doubleqliq/react-native-view-editor

What I would like to ideally do is have a Surface wrapping an AnimatedSurface (the child of my Animated Surface is a GL.Node that allows for image filtering). However, when I wrap a Surface around an animated surface no image shows up. The purpose of the surrounding surface would be to allow you to set the bounds of the crop image. Is this possible?

**Comment by sscaff1** [comment]
The other way to solve this would be to pass in some height, width, and starting coordinates of a surface capture.

```
this.surface.captureFrame({ height: 100, width: 100, startX: 0, startY: 0, ...config });
```

**Comment by gre** [comment]
yeah, by design, Surface does not compose, only GL Component / GL.Node does.

related https://github.com/ProjectSeptemberInc/gl-react-native/issues/86#issuecomment-225214260

**Comment by gre** [comment]
to set the bound of an image, you might implement some sort of `GLCrop` that takes the image and bound and crop the image on the GPU. can inspire from https://github.com/gre/gl-react-image/blob/master/src/Image.js

**Comment by sscaff1** [comment]
I'm actually now working on capturing the entire surface, and then using the native ImageEditor to crop the image after the surface is captured. For some reason though the dimensions of my image are off...When I use capture frame and measure the image, I get an image that is twice the size of the original image I passed into the Surface. Any ideas?

```
  const getImageSize = (image) => new Promise(resolve =>
      Image.getSize(image, (width, height) => {
        console.log(width, height);
        resolve(image);
      })
    );
    const cropImage = (image) => new Promise(resolve =>
      ImageEditor.cropImage(image, {
        offset,
        size,
      }, uri => resolve(uri), () => null)
    );
    return this.surface.captureFrame({ quality: 1, format: 'base64', type: 'jpg' })
    .then(image => getImageSize(image))
    .then(image => cropImage(image))
    .then(uri => uri);
  }
```

**Comment by sscaff1** [comment]
Before I capture

```
1079 537
```

After I capture

```
2160 1074
```

I'm using Image.getSize(imagePath, (width, height) => console.log(width, height)) to measure my image both times...

**Comment by gre** [comment]
Set pixelRatio prop to 1

**Comment by sscaff1** [comment]
Thank you so much for your help. That works great. I'll post my final solution to 
https://github.com/doubleqliq/react-native-view-editor
in case anyone wants to check it out.
