### ISSUE TITLE
Ability to edit highlights and shadows

### ISSUE THREAD

**Issue by sscaff1** [ProjectSeptemberInc/gl-react-native#106]
Is there a way to do this with a shader? My OpenGL is terrible, but if anyone has any code that would do this, I would greatly appreciate it.

**Comment by gre** [comment]
can you explain what you mean (highlights and shadows?), I'm not sure to understand?
Thanks

**Comment by gevorg15** [comment]
I think he's referring to how instagram does their edits.  They have a highlights and shadows features.  Highlights option just adjusts the brightness of the lighters parts of the image and Shadows adjusts the brightness of the darker parts in the image.
