### ISSUE TITLE
Error when using captureFrame()

### ISSUE THREAD

**Issue by sscaff1** [ProjectSeptemberInc/gl-react-native#108]
I was not getting this error using the git repo directly in my project, but when I upgraded to the latest NPM version, I'm now getting this error.

Here is my code:

```
  captureFrameAndCrop(captureProperties = null) {
    const properties = captureProperties || this.getCurrentState();
    const cropImage = (image) => new Promise(resolve =>
      ImageEditor.cropImage(image, properties, uri => resolve(uri), () => null)
    );
    return this.surface.captureFrame({ quality: 1, format: 'file', type: 'jpg', filePath: `${RNFS.DocumentDirectoryPath}/${new Date().getTime()}.jpg`})
    .then(image => cropImage(image))
    .then(uri => uri)
    .catch(error => console.log(error));
  }
```

in the render function:

```
return (
        <AnimatedSurface
          ref={ref => this.surface = ref}
          width={imageWidth}
          height={imageHeight}
          style={animatedStyle}
          pixelRatio={1}
          {...this._panResponder.panHandlers}
        >
          {children}
        </AnimatedSurface>
      );
```

![simulator screen shot sep 14 2016 4 51 01 pm](https://cloud.githubusercontent.com/assets/1554424/18533956/c9c12736-7a9b-11e6-8944-9aa273605cc9.png)

**Comment by sscaff1** [comment]
It actually appears that this is related to upgrade RN to 0.33 rather than gl-react-native. On 0.32 the above works, but on 0.33 I get the above error.

**Comment by st0ffern** [comment]
@sscaff1 what output path do you get with RN 0.33 with RNFS.DocumentDirectoryPath ?

**Comment by gre** [comment]
Mmh, I think it might be related to the AnimatedSurface you use,
maybe there is a bug in https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/src/index.js#L58
maybe RN Animated changed and it's no longer that `.refs.node` I was (weakly) relying on :(

I'll investigate a bit later, feel free to investigate too ;)

**Comment by gre** [comment]
yeah it's definitely this. code has changed here 
https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/AnimatedImplementation.js#L1667

can you try to change the gl-react-native code to:

```
    getGLCanvas: glSurface => glSurface.refs.canvas._component,
```

yeah, this really sucks, but I'm not sure how to do otherwise !?

**Comment by gre** [comment]
if it works, can you provide a PR

**Comment by sscaff1** [comment]
Thanks for the help @gre. I opened up a PR.

**Comment by gre** [comment]
awesome thanks, i'll do a quick check there is no other regression in all examples and i'll release a gl-react-native 2.33 asap

**Comment by sscaff1** [comment]
@gre I opened up another PR - sorry I made a mistake. #111

**Comment by gre** [comment]
it's funny but one of the example use `react-native-material-kit` and they also have a broken regression because of animated change xD

and they recently fix it like this:
https://github.com/xinthink/react-native-material-kit/blob/318e1646d25459b3b137de5e8845dc6fdcc38dbb/lib/mdl/Switch.js#L221

i'll change our code to do the same ducktyping so it's retro compatible ;)

**Comment by devanshujain95** [comment]
Still not able to fix it.
Below is the snippet of what I am doing!

AnimatedSurface: makeSurface({
    View: Animated.View,
    GLCanvas: Animated.createAnimatedComponent(GLCanvas),
    **getGLCanvas: glSurface => glSurface.refs.canvas.refs._component,**
    dimensionInvariant: (value, field) =>
      invariant(
        isAnimated(value) || typeof value === "number" && value > 0,
        "GL.AnimatedSurface: "+field+" must be a strictly positive number OR an Animated object"
      )
  }),
