### ISSUE TITLE
Shaders.setImplementation can be called only once

### ISSUE THREAD

**Issue by gevorg15** [ProjectSeptemberInc/gl-react-native#114]
After upgrading to RN 0.34 and gl-react 2.2.8 and gl-react-native 2.34.0, i'm getting an error from gl-react about Shaders.setImplementation.

<img width="376" alt="screen shot 2016-09-27 at 12 32 17 pm" src="https://cloud.githubusercontent.com/assets/569622/18895299/6bbc6a4c-84cd-11e6-8303-56812c4ef796.png">

It was working fine with RN 0.33 gl-react 2.2.6 and gl-react-native 2.33.0

**Comment by gre** [comment]
that sounds like you might have twice gl-react-native in your project otherwise i'm not sure how it can happen.
can you try to do this:
`npm ls gl-react-native`
and see if it appears more than once

**Comment by gevorg15** [comment]
You are correct.  There were two links.  One was linked via npm repository to a specific version number and the other was a dependency within another module that was point the dependency the github repo.  

Thanks! I've removed the duplicate dependencies and its working as expected now.
