### ISSUE TITLE
[Android] surface.captureFrame() timeout

### ISSUE THREAD

**Issue by jasongaare** [ProjectSeptemberInc/gl-react-native#117]
So due to the current inability to render a transparent `Surface` background on Android, my workaround is to render the surface, then capture the frame and save it locally, then overlay that image in an `<Image>` component in my view. 

My code:

```
<Surface
  ref={(ref) => { this.surface = ref; }}
  backgroundColor="transparent"
  width={viewportWidth(100)}
  height={surfaceHeight}
  onLoad={() => {
    this.surface.captureFrame({
      type: 'png',
      format: 'file',
      filePath: this.tempFile,
    }).then((fileUrl) => {
      this.setState({ edgesUrl: fileUrl });
    }).catch((error) => {
      console.error(error);
    });
  }}
>
```

Based on my testing, on iOS this code works 100% of the time. However, on Android it seems that around 50% of the time the Promise never gets fulfilled, meaning the state does not get set, nor does an error get caught. It seems to hang for some reason, and ultimately I cannot save the captured frame. `onLoad` does seem to get called (based on some console.logs).

I'm not sure how to resolve this issue. Perhaps a feature request would be a way to check if this captureFrame has a timeout? Or does anyone have an idea if there is a better way to implement this?

Also I should add that when it hangs, then I exit the view that contains the `Surface` at that point the catch IS called and it says (`GLCanvas is unmounting`).

**Comment by jasongaare** [comment]
More details. It seems to be device dependent unfortunately.

RN version: 0.32,
gl-react-native: 2.32.0

--Galaxy S5, Android 5.0 worked (33/50) trials
--Galaxy Note 3, Android 5.0 worked (40/50) trials
--Google Nexus 5X, Android 7.0 worked (50/50) trials

**Comment by gevgasparyan** [comment]
I have this issue too, @jasongaare i want to know, is your issue fixed or still you have this ?

**Comment by allthetime** [comment]
Issue still exists on some devices (my friends galaxy s6 for instance) but works fine in simulator. Concerned by how many devices this actually affects. Did you get anywhere with this?

**Comment by wilsonWong951218** [comment]
Any update or solution?
