### ISSUE TITLE
Use TextureView on Android

### ISSUE THREAD

**Issue by robclouth** [ProjectSeptemberInc/gl-react-native#120]
Using [TextureView](https://github.com/google/grafika/blob/master/src/com/android/grafika/TextureViewCanvasActivity.java) instead of GLSurfaceView solves z-ordering issues on android because TextureViews can be arbitrarily layered with transparent backgrounds. More like GLKViews. Maybe you could have a single thread and context driving all of them, more like the iOS version.

**Comment by gre** [comment]
very interesting :)
