### ISSUE TITLE
Can't compile on xcode 

### ISSUE THREAD

**Issue by abrarmusa** [ProjectSeptemberInc/gl-react-native#121]
Getting this error

../node_modules/gl-react-native/ios/GLImage.m:83:37: No visible @interface for 'RCTImageLoader' declares the selector 'loadImageWithURLRequest:size:scale:clipped:resizeMode:progressBlock:partialLoadBlock:completionBlock:'

**Comment by rakannimer** [comment]
Which Xcode version ?

**Comment by gre** [comment]
Can you try 2.35.0-rc.0
?

**Comment by abrarmusa** [comment]
Currently running 2.35.0-rc.0

**Comment by mmeineke** [comment]
2.35.0-rc.0 worked for me. Used xcode 8 and RN 0.35

**Comment by johan-lim** [comment]
I am having the same issue on both 2.35.0-rc.0 and 2.36.0. Using XCode 8.1 and RN 0.32.0

**Comment by gre** [comment]
is this fixed now?

**Comment by st0ffern** [comment]
@gre its working fine here. this may be closed..
