### ISSUE TITLE
Support for RN 0.36?

### ISSUE THREAD

**Issue by gevorg15** [ProjectSeptemberInc/gl-react-native#122]
Are there plans to add support for React Native 0.36?

**Comment by gre** [comment]
`2.35.0-rc.0` should already work there, but I've just released a `2.36.0`.

the example UI is a bit broken (mainly on android) because of `https://github.com/xinthink/react-native-material-kit/issues/261`.
the breaking changes of RN shouldn't affect the lib so it should be fine.
