### ISSUE TITLE
[Android] captureFrame alters colors

### ISSUE THREAD

**Issue by superandrew213** [ProjectSeptemberInc/gl-react-native#124]
Original:
![screenshot_2016-11-06-07-45-16 2](https://cloud.githubusercontent.com/assets/13059204/20043519/7bc5a822-a4da-11e6-9b59-70d5838d5435.png)

Captured Frame:
![screenshot_2016-11-06-07-45-23 2](https://cloud.githubusercontent.com/assets/13059204/20043520/85ddf954-a4da-11e6-8881-f772475df970.png)

Hard to see. If you download them and switch back and forth between them, you will see that the captured frame is slightly more yellowish. This is the original image and nothing else has been applied to it. On iOS both images look identical.

**Comment by gre** [comment]
Do you have opacity somewhere?

**Comment by superandrew213** [comment]
@gre nope, it's just a basic set up. If you recapture the same image over and over again this is what you get ( i think this was about 5 times):

![screenshot_2016-11-07-12-08-47 2](https://cloud.githubusercontent.com/assets/13059204/20051917/32a7f8fa-a51d-11e6-9d68-18059765dbe8.png)

On iOS image doesn't get altered.

**Comment by superandrew213** [comment]
@gre any idea why this is happening?

**Comment by gre** [comment]
Can you share what is your (shader) code doing?
Do you capture in PNG format? (should be lossless..)
I'm not sure where the colorspace issue is (fresco / opengl / capture code encoding)

**Comment by gre** [comment]
if you use JPEG, it's lossless so you might have this issue. related http://stackoverflow.com/questions/10908707/why-the-color-of-the-image-changed-when-it-compressed-by-bitmap-compressformat-j

**Comment by superandrew213** [comment]
There is no shader applied to it in the example above. It's pretty much just:
```
<Surface>
  <GLImage/>
</Surface>
```

You mean JPEG is lossless and PNG is not? I am using JPEG but am not seeing any issues with it on iOS at all. I tested it using PNG and this is the result of recapturing the same image 5 times:

![7709c344-8eb8-4a43-b36f-4c3518d17d21](https://cloud.githubusercontent.com/assets/13059204/20966632/fd3a84fa-bcc6-11e6-9918-96d5a5d44d01.jpg)

**Comment by gre** [comment]
I don't think we can guarantee the JPEG implementation to be the same cross platform.
However, maybe there is something weird in the quality option, do you use any value?

the capture method except a quality from 0.0 to 1.0 but

Java Bitmap expect a value from 0 to 100. the code should properly make to that range, but however do you think this code is correct? : i've just seen this code https://github.com/ProjectSeptemberInc/gl-react-native/blob/539a73f6b91a626125f6de42c126550e33f7e7f3/android/src/main/java/com/projectseptember/RNGL/GLCanvas.java#L200 . I'm wondering it it should be 100.0 * quality ? (wondering if quality is just convert and maybe it's messed up to be converted to 0.)

**Comment by superandrew213** [comment]
I have quality set to 1 so that would result in 100.

I think that code is fine. It will convert any decimal between 0 - 1 to an integer between 0 - 100. How do you think it would get messed up?

**Comment by st0ffern** [comment]
@superandrew213 are you using pixelRatio ?

**Comment by superandrew213** [comment]
@stoffern yes, to capture an image with the same size as the original.

**Comment by st0ffern** [comment]
would you just try to not set the value and see if the same thing happens?

**Comment by superandrew213** [comment]
Yep, already tried it. Outcome is worse.

**Comment by gre** [comment]
nevermind, I just had a doubt with precedence of `((double)100) * 0.7` vs `100 * ((int) * 0.7)`. first case happen

**Comment by gre** [comment]
have you tried PNG, see if the bug happens too?

**Comment by superandrew213** [comment]
Yes tried PNG, this was the result https://github.com/ProjectSeptemberInc/gl-react-native/issues/124#issuecomment-265428850

**Comment by gre** [comment]
oh sorry! missed that.
mmh sounds like something is wrong about Android impl color space.

**Comment by superandrew213** [comment]
@gre any idea how we can fix this? If you could point me in the right direction, I can try to fix it.
