### ISSUE TITLE
Unnecessary use of Android permissions: INTERNET & ACCESS_NETWORK_STATE

### ISSUE THREAD

**Issue by IjzerenHein** [ProjectSeptemberInc/gl-react-native#126]
Hi, I noticed that the `AndroidManifest.xml` file includes permissions for both INTERNET and ACCESS_NETWORK_STATE.
Is there is a particular reason for this and are these permissions really necessary by this package?
If not, these should be removed in my honest opinion.

I'll gladly help by creating a PR for this, but thought I'd ask first in case they are needed by the library.

cheers, Hein

**Comment by gre** [comment]
I think they are for fetching images.

**Comment by gre** [comment]
but maybe they should be optional, i don't have good experience on what's good practice in this subject in Android.

**Comment by IjzerenHein** [comment]
Well I guess if this library is doing the actual fetching of the images itself, then they should be included. If the fetching is performed by core functionality of react-native then I would certainly not include them. Could you point me to a resource which illustrates the fetching of images?

**Comment by gre** [comment]
basically using Fresco: https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/android/src/main/java/com/projectseptember/RNGL/GLImage.java#L57

**Comment by IjzerenHein** [comment]
Alright, that looks indeed like a valid case. I think we should keep this in and I'll close the bug.

And for those people that want to remove unwanted permissions, you can use this construct in your AndroidManifest.xml:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
		xmlns:tools="http://schemas.android.com/tools"
    package="com.atogear.arion"
    android:versionCode="1"
    android:versionName="1.0">

    <!-- Remove permissions not required by this app -->
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" tools:node="remove"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />
</manifest>
```

Thanks for the quick responses!
