### ISSUE TITLE
[RN Android] Only the first child RN component of the gl react native surface get displayed  (image + text)

### ISSUE THREAD

**Issue by ogostus** [ProjectSeptemberInc/gl-react-native#127]
#I'm trying to reproduce the exemple in the gl react native repo, the one with mutiple components, but only the first component get displayed, it worked for me once, but now it doesn't and I don't know why

here is a snippet:

`<Surface 
            width={Width} 
            height={Height} 
            ref="cropit" 
            autoRedraw 
            visibleContent
            // eventsThrough
          >
<Effects  filter={this.props.effects.filter} >
 <View key="filters" style={{flex:1, width:Width, height:Height}} >
<Image   style={{height: Height, width: Width}} source={{ uri: this.propst.uri }}/>
                                <Text
                                  style={{
                                        position: "absolute",
                                        bottom: 0,
                                        left: 0,
                                        width: 256,
                                        height:180,
                                        textAlign: "center",
                                        color: "#f16",
                                        backgroundColor: "transparent",
                                        fontWeight: "400",
                                        fontSize: 24,
                                        letterSpacing: 0                       
                                  }}
                                >
                                  hallooooo!!
                                </Text>
                  </View>        
</Effects>                 
</Surface>`

if I place the text first, the image won't be displayed, and now the image is displayedand the text is hidden.

Anyone can help? i'm stuck at this.

**Comment by gre** [comment]
I think you have to re-render when the image loads. like you can probably do something like `onLoad={() => this.forceUpdate()}` on the image.

This feature is quite experimental and I would not be surprise there are weird issues at the moment.
