### ISSUE TITLE
flash screen  and multiple texture maps 

### ISSUE THREAD

**Issue by ben00007** [ProjectSeptemberInc/gl-react-native#128]
when I   use gl-react-native to  realize multiple texture maps  ,meet some issue ,pls help me to fix it ,Thanks.

First, there will be flash screen problem.,The following is an important code.
 `<Surface width={debugSize} backgroundColor= "transparent" > height={debugSize} 
   <Layer> 
     {img1} 
     {img2} 
   </Layer> 
</Surface> `

When I want  to add a img map, for example ,it will flash screen .
 `<Surface width={debugSize} backgroundColor= "transparent" > height={debugSize} 
	<Layer> 
		<Layer>
			{img1} 
			{img2} 
		</Layer> 
		{img3} 
	</Layer> 
</Surface> `
How to solve it ? Thanks ! btw,Layer  is the example component of the project.

Second, when img1 and img2 have the  different dimensions , how to specify the location and size  of the img2 on the img1. Thanks !

Third , Are there the better  method  to  use gl-react-native  realize multiple texture maps,   Thanks.

**Comment by gre** [comment]
have you tried setting the `preload` prop on Surface ? it should wait images to load before rendering.

**Comment by gre** [comment]
doc https://github.com/ProjectSeptemberInc/gl-react/blob/master/docs/api/Surface.md#props-of-surface

**Comment by ben00007** [comment]
Thanks,I have  tried to set preload ={true}, but the issue of  flash screen is the same  ,

This issue has puzzled me for a long time,  pls help me .Thanks!
