### ISSUE TITLE
[iOS] Build failed ("React/RCTConvert.h file not found")

### ISSUE THREAD

**Issue by skizzo** [ProjectSeptemberInc/gl-react-native#129]
Hi,

I was following the [installation instructions](https://github.com/ProjectSeptemberInc/gl-react-native#installation) (without CocoaPods) for getting gl-react-native to work on iOS. Problem is, RNGL spits out the following error(s):

![screen shot 2017-01-17 at 14 51 00](https://cloud.githubusercontent.com/assets/2892572/22022947/69094d0c-dcc4-11e6-9a88-91786257846d.png)

I'm guessing it's because the imports have `React/` prefixed, all of my other iOS libraries don't have that prefix; they all import via `#import "RCTUIManager.h"`, which works just fine.

So I'm guessing it has something to do with the **header search paths** in XCode, but I can't get my head around a solution. Can anybody help? Thanks!

**Comment by gre** [comment]
can you tell me your version of gl-react-native and react-native?

**Comment by gre** [comment]
`#import "RCTUIManager.h"` should no longer works in react-native 0.40.0 , there were [breaking changes](https://github.com/facebook/react-native/releases/tag/v0.40.0), so gl-react-native 2.40.0 only works with react-native 0.40.0, if you have older version, use a gl-react-native version that works with it.

**Comment by skizzo** [comment]
Makes sense! Since I'm using `react-native 0.37.0`, I have to use `gl-react-native 2.37.0`, thanks for the help!

**Comment by paintedbicycle** [comment]
Seeing this issue again using `react-native 0.51.0` and `gl-react-native 2.48.0`

**Comment by Fsarmento** [comment]
Have you tried adding "${PODS_ROOT}/Headers/Public/React" to Header search paths?

Select Pods as project, RNGL as target from the list of targets. Then, on Build Settings, search for "header search paths" (make sure you have "All" selected in the filter area). Click on the paths and add "${PODS_ROOT}/Headers/Public/React" as a new line.

<img width="1052" alt="hsp" src="https://user-images.githubusercontent.com/18128610/44336973-03fd6d00-a471-11e8-9e17-8ec40f55ff9d.png">
