### ISSUE TITLE
Warp perspective - possible with this lib?

### ISSUE THREAD

**Issue by skizzo** [ProjectSeptemberInc/gl-react-native#130]
Hi,

is it possible to use `gl-react-native` to implement a function similar to [OpenCV's warpPerspective](http://opencvexamples.blogspot.com/2014/01/perspective-transform.html)?
My goal would be to _put a "poster"_ on top of the image of an empty wall in a perspective defined by 4 corner points.

Obviously, I don't know much about OpenGL (yet). Any help is much appreciated!

![perspective transform](https://cloud.githubusercontent.com/assets/2892572/22026312/b39d116c-dcd0-11e6-8427-b90c4dc7cceb.JPG)

**Comment by gre** [comment]
if we would have access to vertex data / shader, it would be easy but gl-react-native currently does not expose that.

that said, it's possible to get it done in a Fragment shader too. just need to figure out the formula to apply.

i wish this question was answered: http://stackoverflow.com/questions/31925583/how-to-use-a-3x3-2d-transformation-in-a-vertex-fragment-shader-metal
but it's probably somewhere on the internet
