### ISSUE TITLE
[Android] Old Surface get redrawn over new Surface in different Scene

### ISSUE THREAD

**Issue by gmlion** [ProjectSeptemberInc/gl-react-native#131]
I'm having this strange behaviour on Android, where the old Surface get drawn over the new Surface in another Scene. To be noted that the new Surface can be seen _behind_ the old surface, for example scrolling it so that the old Surface doesn't cover it. The old Surface image doesn't scroll, so it only occupies the intersection between its size and the new Surface.

I'm using the fragment shader to mix some textures, doing almost the same thing on the two Scenes.

**Comment by gmlion** [comment]
I resolved exposing GLCanvas.setZOrderMediaOverlay as React Native prop. Setting it to true put the new SurfaceView above the previous.

**Comment by gre** [comment]
sounds good. thanks. i'll release a patch asap
