### ISSUE TITLE
There are no RNGL.xcodeproj in node_modules/gl-react-native

### ISSUE THREAD

**Issue by Phenek** [ProjectSeptemberInc/gl-react-native#133]
Hello Guys,

I just install gl-react-native with:
_"npm i --save exponent"
_"npm i --save gl-react"
_"npm i --save gl-react-native"

but for IOS I can't find the RNGL.xcodeproj in node_modules/gl-react-native

Hope you can help me.
Let me know :-)
regards,

**Comment by Phenek** [comment]
By default installation,
the version of gl-react-native & gl-react is 3.0.0-alpha.2

I had to change the version in my package.json:
    "exponent": "^13.1.0-rc.2",
    "gl-react": "^2.2.4",
    "gl-react-native": "^2.40.1",
    "react": "15.4.1",
    "react-native": "^0.40.0",

**Comment by gre** [comment]
yeah the 3.0.0 is not yet ready concerning React Native
