### ISSUE TITLE
gl-react-native: the native module is not available

### ISSUE THREAD

**Issue by Phenek** [ProjectSeptemberInc/gl-react-native#134]
Hello guys,

I trying to install gl-react-native, but I got this error:
gl-react-native: the native module is not available
NativeModules.GLCanvasManager is undefined

I configured it like this for IOS:
[capture d ecran 2017-01-24 a 12 22 45](https://cloud.githubusercontent.com/assets/4518686/22245371/d83e588c-e22f-11e6-9207-ae870eca160f.png)

I got :
    "gl-react": "^2.2.4",
    "gl-react-native": "^2.40.1",
    "react": "15.4.1",
    "react-native": "^0.40.0",

Hope you can help me! :-)
regards,

**Comment by gre** [comment]
mmh, that should be fine regarding your screenshot. have you tried to restart the packager and redeploy?

**Comment by Phenek** [comment]
Hey,
_I restarted the packager a lot of time.
_uninstall et reinstall gl-react-native ans the others gl-*
_rm -rf node_modules too
-npm i

my import are like below:
import { Surface } from 'gl-react-native';
import GL from "gl-react";
import ImageCrop from 'react-native-image-cropper';

I got still this issue 
![capture d ecran 2017-01-24 a 14 44 31](https://cloud.githubusercontent.com/assets/4518686/22249631/146aae96-e244-11e6-9da9-fd9e5bff4bd3.png)

Let me know if you have any idea
regards,

**Comment by gre** [comment]
can you try to run 

```
npm ls react-native
npm ls gl-react-native
npm ls gl-react
```

to see if there is not a weird version, nor some dups.

thanks

**Comment by Phenek** [comment]
└── react-native@0.40.0 
└── gl-react-native@2.40.1 
└── gl-react@2.2.8 

my package.json is like below now:
    "gl-react": "^2.2.8",
    "gl-react-native": "^2.40.1",
    "react": "15.4.1",
    "react-native": "^0.40.0",

Everything seems to be fine.

**Comment by Phenek** [comment]
Seems to be a conflict with react-native 0.40

Cause now I can compile on xcode the problem is solved
But when I compile with "react-native run-ios" on Terminal
The module is not found..

Quite a bit strange

**Comment by gre** [comment]
mmh weird! maybe we need to raise the problem in react-native repo, as soon as we figure out a minimal repro.. I'm not sure where the problem is, it can be a problem in the RNGL xcode project, a configuration problem in your app, or a bug in react native.

**Comment by brianinator** [comment]
0.40 changed the headers which was a breaking change perhaps it's related to that.

**Comment by gre** [comment]
RN 0.40 definitely is a breaking changes but it should just work transparently if you switch to gl-react-native 2.40.x

**Comment by gre** [comment]
it worked for me when I switched the example app. Can anyone tell me if they succeed to port to 2.40.x and if not do you get the same issue?

**Comment by brianinator** [comment]
My project is not at RN 0.40.0 yet. I needed to go to 2.39.0 for this module to get it to build. Also, just fyi make sure to include the link library in Build Phases.

**Comment by NISHANTSINGHREWSAN** [comment]
can i use it with

"dependencies": {
    "gl-react": "^2.2.9",
    "gl-react-native": "^2.40.2",
    "querystring": "^0.2.0",
    "react": "^0.14.8",
    "react-native": "^0.24.1",


}


plz reply

**Comment by gre** [comment]
yes I think it should work

**Comment by NISHANTSINGHREWSAN** [comment]
but@gre its not working

**Comment by ignivarahulsaini** [comment]
Hi @NISHANTSINGHREWSAN 
I have tested and found the problem is with gl-react-native. when we run npm install and files of package not downloaded. I have downloaded them manually and run install with files, it worked. :)
Hope this helps you @NISHANTSINGHREWSAN

**Comment by gre** [comment]
please provide more info, error log or something.

I have the latest lib working fine via NPM so i'm not sure what's wrong here.

please also tell what this command returns:

`npm ls gl-react gl-react-native react-native`

because what you put in package.json might not reflect what you have in node_modules (especially with the `^` semver, there might be something wrong)

**Comment by st0ffern** [comment]
`npm i -S gl-react gl-react-native`

**Comment by pi-sw** [comment]
I encounter the same problem, `npm ls gl-react gl-react-native react-native` gives me:
```├── gl-react@2.2.10 
├── gl-react-native@2.43.0 
├── react-native@0.46.2 
└─┬ react-native-image-cropper@0.3.0
  ├── gl-react@2.2.10  deduped
  └── gl-react-native@2.43.0  deduped
``` 

any idea?

**Comment by pi-sw** [comment]
ok, RTFM: https://github.com/gre/gl-react/tree/master/packages/gl-react-native#configure-your-react-native-application

`npm link gl-react-native ` is *not* enough.

**Comment by anderfsilva** [comment]
Same here.

**gl-react@2.3.1**
**gl-react-native@2.47.0**
**react-native@0.48.4**
**react@16.0.0-alpha.12**

Has anybody looked into this? 
Is there any other option?

**Comment by st0ffern** [comment]
Android?

So you have `compile project(':gl-react-native')` in you build.gradle?

**Comment by guitar9** [comment]
have you configured it correctly?
[https://github.com/gre/gl-react-native-v2](url) 

I had the same problem and get it solved by configuring it correctly

**Comment by st0ffern** [comment]
define configuring it correctly

**Comment by guitar9** [comment]
do this stuff:

```
android/settings.gradle:: Add the following snippet
include ':RNGL'
project(':RNGL').projectDir = file('../node_modules/gl-react-native/android')
android/app/build.gradle: Add in dependencies block.
compile project(':RNGL')
in your MainApplication (or equivalent) the RNGLPackage needs to be added. Add the import at the top:
import com.projectseptember.RNGL.RNGLPackage;
In order for React Native to use the package, add it the packages inside of the class extending ReactActivity.
@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
	new MainReactPackage(),
	...
	new RNGLPackage()
  );
}
```

**Comment by moeedshahid** [comment]
i cant find isAnimated under this path 
import isAnimated from "gl-react/src/isAnimated";

followed this 
https://www.npmjs.com/package/react-native-gl-image-filters

**Comment by leandromlopes** [comment]
@stoffern  did you have any luck installing on Android?

**Comment by st0ffern** [comment]
Have not had any problems.. but i dont use `react-native-gl-image-filters`

**Comment by saly2310** [comment]
Also I got the issue on iOS.

**Comment by saly2310** [comment]
I also got the issue on iOS.

**Comment by saly2310** [comment]
I aslo got the issue on iOS
My package json : 
"react-native": "^0.53.3",
