### ISSUE TITLE
Cannot evaluate module RNGL : Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by abrown1982** [ProjectSeptemberInc/gl-react-native#136]
Having an issue compiling from a totally clean install of react-native and gl-react-native on android.  Fairly sure I have followed instructions correctly and without gl-react-native the app is building and running as expected, however after installing gl-react-native I am getting the error:

    FAILURE: Build failed with an exception.

    * What went wrong:
    A problem occurred configuring project ':app'.
    > Cannot evaluate module RNGL : Configuration with name 'default' not found.

Good chance this is something stupid I'm doing as I have just started looking into react-native to see if it can cope with a project I have.  Only thing which is jumping out at me is that the path suggested "../node_modules/gl-react-native/android" does not seem to have the "android" folder in it? After spending a while banging my head against a wall any help would be appreciated.

Thanks

**Comment by gre** [comment]
can you make sure you are on v2 of gl-react-native? (the v3 alpha is not yet working)

```
npm ls gl-react-native
```

thanks

**Comment by abrown1982** [comment]
Thanks @gre exactly right, I was on v3 of both gl-react-native and gl-react.  Forcing latest v2 versions of both and its compiling fine.  Thanks for the help.

**Comment by Im-Goutham** [comment]
Getting same issue. Which version to use ?
