### ISSUE TITLE
Surface webglContextAttributes={{ preserveDrawingBuffer: true }} on native does not work

### ISSUE THREAD

**Issue by jukes** [ProjectSeptemberInc/gl-react-native#137]
Hi, I'm trying to port this example to react-native: https://gl-react-cookbook.surge.sh/paint
But right now the drawing is erased when I touch the screen again. I suspect that this property on the <Surface is not doint anything on native: webglContextAttributes={{ preserveDrawingBuffer: true }}

How do I preserve the Drawing Buffer on gl-react-native?
Thanks a lot

**Comment by gre** [comment]
Actually you are trying to port a v3 example to the v2. Sorry to have made this confusing.

v2 is much more limited and won't allow to do things like buffering / preserving pixels because of its limited design.

We're working on a v3 for RN. If you use Exponent, gl-react-exponent should be working (still alpha)

**Comment by jukes** [comment]
Oh, I see.. Yeah I am using v2 actually because I wanted to avoid using exponent. Thanks for the help and the hard work on the library.

**Comment by superandrew213** [comment]
@gre just to clear things up. Will gl-react-native v3 be available without using exponent?

**Comment by gre** [comment]
@superandrew213 yeah it will, probably via using exponent 'detach' new command that allow to detach exponent into a standalone library that you can depend on. I'm going to look at this soon. There are still a few pending things that the Exponent GL implementation need to fix but we should be close to ~ same level of features :)

**Comment by st0ffern** [comment]
Dont understand what is so great with exponent vs pure react-native..?

**Comment by superandrew213** [comment]
@stoffern this explains it quite well [What is the difference between Exponent and React Native?](http://stackoverflow.com/questions/39170622/what-is-the-difference-between-exponent-and-react-native). Personally I still prefer just react-native, even though exponent might speed up things and has some nice tools.

**Comment by gre** [comment]
Exponent recently introduced the GLView that is a complete implementation of WebGL on top of OpenGL. You can do normal WebGL in the JS side! It works fine so far, a few glitch that are pending to be fixed but it should soon be good to use.

So far, the gl-react-native implementation was covering a small subset of what you can do in WebGL/OpenGL (and was already tricky to maintain, bunch of ObjC files, bunch of Java files). Here, relying on this GLView will allow gl-react to focus on its features and API (no more native code on our side). The gl-react v3 codebase is much more shared. Also this allowed me to improve a lot gl-react in that v3. Thinking that 'someone is going to implement WebGL for me' was a real relief in making gl-react better. gl-react can provide a nice abstraction while the low level impl of GLView just gives you the imperative webgl context object and they can focus on maintaining/stabilizing/improving at a more "common level" that is that Exponent GL View.

**Comment by gre** [comment]
finally, I really like that the WebGL implementation is decoupled from the opinionated gl-react API (react & functional styled). People should be free to either do vanilla WebGL if they want, or maybe use gl-react if they are happy with it.

**Comment by st0ffern** [comment]
Great answer 👍

**Comment by jukes** [comment]
Great feed back guys.
