### ISSUE TITLE
Reference to Components

### ISSUE THREAD

**Issue by mrThinBone** [ProjectSeptemberInc/gl-react-native#138]
How do I set reference to Surface, GLImage, etc...?

I have tried but seem not work as react native components like View
`<Surface props...><GLImage ref="some_tag" props... /></Surface>`

**Comment by gre** [comment]
you can't do that in the v2. what you put inside the Surface don't have references because the limited design of the 2.x.

Hopefully the v3 will allow and should be soon available for React Native.

**Comment by mrThinBone** [comment]
@gre actually, I don't know how to save adjusted image (brightness, contrast, saturation, etc), Surface.captureFrame(...) doesn't support that purpose.
