### ISSUE TITLE
ndarray support

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react-native#14]
This is a separate issue for implementing https://github.com/ProjectSeptemberInc/gl-react/issues/14 in the React Native context.

Implementation is not so trivial:
- there is no support for typed array in JS<>ObjC RN bridge (see https://github.com/facebook/react-native/issues/1424 )
- Ideally, we should implement all cases like `gl-texture2d` do: https://github.com/stackgl/gl-texture2d/blob/40502cc8b80fc8521b07a1d27739659215da763e/texture.js#L461-L530 (but as a first step, we could just support a more limited subset of formats..)

**Comment by robclouth** [comment]
Does [this pull request](https://github.com/facebook/react-native/pull/6961) mean that sending TypedArrays across the bridge is now possible?

**Comment by gre** [comment]
looks interesting. but it looks like it's restricted to Web Socket at the moment. It also looks like it's implemented by converting back to `base64` string, so it's not very best we can do I guess.

https://github.com/facebook/react-native/issues/1424 is still opened
