### ISSUE TITLE
how to transparent background

### ISSUE THREAD

**Issue by mrThinBone** [ProjectSeptemberInc/gl-react-native#140]
Hi, as title how can I do it.
I provided an image which has .PNG format and its background is transparent. And GLImage displayed background as black.
```
<Surface ...>
   <ImageFilter ...>
       <GLImage .../>
   </ImageFilter>
</Surface>
```
I have tried to change holder format from RGB_888 to ARGB_8888 in native code ([GLCanvas.java](https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/android/src/main/java/com/projectseptember/RNGL/GLCanvas.java) line 98) but no luck

**Comment by st0ffern** [comment]
add backgroundColor to your `<Surface>`
see docs: https://github.com/ProjectSeptemberInc/gl-react/blob/master/docs/api/Surface.md#props-of-surface

**Comment by mrThinBone** [comment]
@stoffern still not working
`<Surface backgroundColor={"transparent"}>`

**Comment by st0ffern** [comment]
`transparent` is not a valid color format in `react-native`

**Comment by st0ffern** [comment]
@gre this can be closed..

**Comment by gre** [comment]
actually transparent is valid ( https://facebook.github.io/react-native/docs/colors.html ) and should be accepted by the lib but I think there is an issue in the Android implementation with opacity.
Android is a pain to get opacity & z-indexing right.

My goal is to try to get it solved in the v3 that will solve most of the issues we have on the repo.

**Comment by egunsoma** [comment]
@gre @mrThinBone @stoffern Hey guys I'm still struggling with this. Here is what I have:
```
<Image
      source={{ uri: image }}
      style={{ width, height }}
    >
      <Surface
        ref="surface"
        style={{ backgroundColor: "transparent" }}
        setZOrderOnTop={true}
        {...this._panResponder.panHandlers}
        width={height}
        height={height}>
        <GL.Node
          shader={shaders.oneFingerResponse}
          backgroundColor="transparent"
          uniforms={{ pressed, position, cover, points, pointsCount }}
        />
      </Surface>
    </Image>
```

The idea is that the image will be visible, where the shader returns transparent color. The shader returns `gl_FragColor = vec4(0., 0., 0., 0.);`  when I want transparency. 

On iOS it works fine, but on Android it becomes black, instead of transparent. Is there anything I can do?

If I give the Surface `backgroundColor={"transparent"}`, I get an error:
```
console.error: "Shader 'oneFingerResponse': uniform 'position' at index 0, invalid number: 'NaN'", [null,null]
```

**Comment by computerjazz** [comment]
`<Surface backgroundColor="transparent">` worked for me
