### ISSUE TITLE
How to implement this to video ?

### ISSUE THREAD

**Issue by RZulfikri** [ProjectSeptemberInc/gl-react-native#141]
Hi, i want to create video filtering like image. i already try the image and it work. i already try from sample, but that's for web. how if i want do it to react-native ?

Thanks

**Comment by gre** [comment]
gl-react-native v2 implementation don't allow that.
I hope to support this in the incoming v3.

**Comment by RZulfikri** [comment]
i hope that feature available as soon as possible..

thanks.

**Comment by gre** [comment]
it probably will not be in the initial v3 release but it will definitely be a milestone after the initial release.

**Comment by thozh** [comment]
any news on this please ?
