### ISSUE TITLE
[Android] Build failed : ":gl-react-native:downloadJSCHeaders" FAILED

### ISSUE THREAD

**Issue by thomaslecoeur** [ProjectSeptemberInc/gl-react-native#145]
Hi !

I have an issue during the build of my app on Android, I get this error : 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gl-react-native:downloadJSCHeaders'.
> INSTANCE
```

I linked the library with `react-native link gl-react-native` before building.

I'm using gl-react-native as a dependency of [react-native-image-cropper](https://github.com/stoffern/react-native-image-cropper).

Any idea ?

Thanks !

**Comment by gre** [comment]
which version? `npm ls gl-react-native`

**Comment by gre** [comment]
here is what I think of this error:

- you have installed the latest 3.x version which is in alpha (3.0.0-alpha.4) and not yet ready (somehow i wish this was not considered by NPM not released :'( ) **please stay on v2 for now.**
- that said, the v3 alpha should work, so
  - either it's a bug
  - or you don't have internet / behind a proxy when you where building? (it needs to download some JavaScriptCore headers)

**Comment by gre** [comment]
on my second point, it's effectively a weird "bug", but solved by adding some extra conf in the build (that needs to be manually added).
all will be explained in the README.md of gl-react-native v3.
