### ISSUE TITLE
Color problems in Modal

### ISSUE THREAD

**Issue by st0ffern** [ProjectSeptemberInc/gl-react-native#147]
When used in `Modal` the GL view will render with a slight dark color overlay

**Comment by st0ffern** [comment]
adding `transparent={true}` to Modal solves the problem..

**Comment by IjzerenHein** [comment]
Indeed it is, very strange. Thanks for the find.

**Comment by gre** [comment]
i wonder if https://github.com/gre/gl-react-native-v2/commit/9a13ffa9298b3f2e2f42ac1781e78df70067c935 will fix it, going to release a minor in a few hours
