### ISSUE TITLE
Apply shader without rendering surface

### ISSUE THREAD

**Issue by thomaslecoeur** [ProjectSeptemberInc/gl-react-native#152]
Hello !

I'm trying to apply a special shader when the user take a picture. Then I only want to get the generated PNG from the surface .captureFrame() method. Therefore I don't need to render the surface.

How can I manage to do that ?

Here's my Surface component (that doesn't need to be rendered)

```
_renderImage() {
    return (
      <Surface ref={(component) => {
        this._GLRenderedImage = component
      }} onLoad={this._onImageRendered.bind(this)} preload={true} autoRedraw={false} visibleContent={false}
               width={300} height={200}>
        <BookPageOptimize>
          <GLImage imageSize={{width: 300, height: 200}} source={{uri: "http://i.imgur.com/iPKTONG.jpg"}}/>
        </BookPageOptimize>
      </Surface>
    )
  }
```

Thank you !

**Comment by b3nab** [comment]
@Thomeuxe did you figure out how to apply shaders without render the surface in react-native?
