### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by TimoRuetten** [ProjectSeptemberInc/gl-react-native#158]
I tried to get the examples work but there seems to be a problem with my installation. I redid the installation now several times but none of them seems to work.

After the installation for iOs I tried - just for fun - to build the app via XCode and this error failed the build:

```
Failed to load:
#import <React/RCTJSCExecutor.h>
In: EXGLView.m
```

What I have done:
react-native init
npm i gl-react-native --save
npm i gl-react --save
moved the .xcode file from node_modules/gl-react-native to Libraries of my app in xcode
added in **app** => _targets_ **app** libRNGL.a
inserted your helloGL example.
Result: Just a red dot
inserted the animated example
Result: Just a white screen

Am I missing smth ? Also: The first time the error came that module gl-react was not found so I had to install it.

#### library version

```bash
├── gl-react@3.6.0 
└── gl-react-native@3.6.0 
```

A screenshot of my settings:
<img width="1022" alt="screen shot 2017-06-19 at 10 02 25" src="https://user-images.githubusercontent.com/7010059/27266817-850c8688-54d6-11e7-9cc8-47e96407f32e.png">

**Comment by TimoRuetten** [comment]
**Info**
I now saw an error in the remote console:

> Warning: Native component for "EXGLView" does not exist

**Comment by st0ffern** [comment]
Again, either use version 2.0 or post this a v3.0 repo. 
Se other issues

**Comment by gre** [comment]
as @stoffern said and as written in the comment when you write a new github issue, this repo will only tracks the v2 now. please recreate on https://github.com/gre/gl-react *– feel free to suggest any change in README or somewhere so these repo split is more straightforward.*


I have not checked the v3 against latest RN but there might be something not working there (also need to merge pending PR in gre/gl-react ) – i'm currently in vacation but going back to France in a few days and i'll check these. feel free to fork / PR yourself if you want to help ;)

**Comment by TimoRuetten** [comment]
Oops! Sorry for this! I copied my issue to the v3 board and in the meanwhile I will check if I get v2 to work.
