### ISSUE TITLE
IOS Compile error 'React/RCTJSCExecutor.h' file not found #import 

### ISSUE THREAD

**Issue by tonypee** [ProjectSeptemberInc/gl-react-native#159]
WIth the latest react-native, after adding the Library and Linking it, i run for Iphone and get the error:

/Users/tpee/repos/yigg/node_modules/gl-react-native/ios/EXGLView.m:7:9: fatal error: 'React/RCTJSCExecutor.h' file not found
#import <React/RCTJSCExecutor.h>
        ^
1 error generated.

It cannot find the 'RCTJSCExecutor.h' this exists in:  node_modules/react-native/React/RCTJSCExecutor.h 

should i have to do anything else to make it work?

**Comment by gre** [comment]
you probably meant to issue that on v3 (this repo only tracks v2) – v3 repo is https://github.com/gre/gl-react

there is probably a bug with latest react-native and i'll try to address in the week https://github.com/gre/gl-react/issues/128
