### ISSUE TITLE
Shader failed to compile

### ISSUE THREAD

**Issue by chiformihai** [ProjectSeptemberInc/gl-react-native#160]
#### library versions
gl-react@2.2.10 
└── gl-react-native@2.42.3 
react-native@0.45.1

I'm trying to create a Slideshow (using gl-transitions) and I copy pasted the code from the example, except that I don't use a TransitionGenerator, instead I want to use a single transition.
So everything is exactly the same, except my shaders are defined as:

```
const shaders = GL.Shaders.create({
  slideshow: {frag: GLTransitions.find(t => t.name === 'GlitchDisplace').glsl}
});
```

The problem is that whatever transition I'm trying to use it throws me the error: 

> Shader <> failed to compile: not a program

I tested both on simulator and physical device but I'm getting the same error.
Does anyone know why this happens? Any help would be much appreciated. Thanks

**Comment by gre** [comment]
can you `console.log( GLTransitions.find(t => t.name === 'GlitchDisplace').glsl )` ?

it sounds like this code would work with the former `glsl-transitions` but not the new `gl-transitions`:
If you use the latest gltransitions it probably won't work, you need to wrap it in some GLSL code like in https://github.com/gre/gl-transition-libs/blob/master/packages/react-gl-transition/src/GLTransition.js#L50-L66

**Comment by chiformihai** [comment]
So I upgraded gl-react and gl-react-native to 3.7.0, and I mananged to make the app run, except that now no matter what I try to render, it just won't show on the screen.
I tried using 'react-gl-transition'' GLTransition component to implement the Slideshow and also tried using a plain Node to just see if anything renders on the screen, but with no luck.
Also, Surface's **onLoad** and **onPress** are not called

**Edit**: also the app freezes

**Comment by gre** [comment]
how do you know onLoad/onPress are not called? it's important to note that chrome debugger won't work in gl-react-native 3 (in case you where using the console to log things)

note that the initial problem is independent of using v2 or v3 (you can use either, just know that the v3 is more experimental) , (you can fork the code of react-gl-transition if you want to stay on v2)

**Comment by gre** [comment]
it would be helpful if you paste a snippet that reproduce the problem

**Comment by chiformihai** [comment]
You are right, I was using the chrome debugger.

Here is my current implementation:
[Main screen](https://gist.github.com/chiformihai/18bacd3952a8dc2ab491f43a97ab7039)
[Slideshow](https://gist.github.com/chiformihai/accc395be395e48112ec6dd05f753bfb)

This is the current result:
![image](https://user-images.githubusercontent.com/8382203/27863446-d907d4c2-6192-11e7-8ce9-f782526de658.png)

Thank you for helping :)

**Comment by chiformihai** [comment]
I found what was wrong with my code. There are actually 2 issues:
The app was was freezing because I was passing _height_ and _width_ as props to the **Surface** component instead of setting them in the **style**.
The second problem is that I was using **Shaders.create()** to create my transition and since I'm using _react-gl-transition_, **GLTransition** should receive the proper transition object.
After these updates the app doesn't freeze anymore, but nor the images are loaded.
I'm getting _"uniform t: no loader found for value: ${imageUrl}"_, where imageUrl is the images that I'm trying to render

**Comment by chiformihai** [comment]
I'm pretty stuck at this point, so any suggestions would be really helpful :)

**Comment by gre** [comment]
can you show me the part where you send the uniform `t` , what value do you use?

**Comment by chiformihai** [comment]
I'm using the same code from the cookbook and observed that the error happens at this line:
`<LinearCopy>{from}</LinearCopy>` in the _Slideshow_ component, so LinearCopy doesn't work on react-native?
Also, I tried using _Image_ from _gl-react-native_ instead of _LinearCopy_ but it throws me 

> Failed to construct 'Image': Please use the 'new' operator.

In the end I created a _Saturated_ component, as it can be seen in the example, and rendered the images using it and it worked, but I'm getting some warnings (Surface children does not contain any discoverable node) and when the transition should kick in, nothing happens (except of a glitch)

**Comment by gre** [comment]
Ok but what do you set in that ’from’ value? The error seems to indicate that value is wrong somehow, but maybe it's a bug.

Can you also make sure you don't have duplicated libs with 

    npm ls gl-react

**Comment by chiformihai** [comment]
The outcome of npm ls gl-react is _empty_, so no duplicate libs.

In _from_ I'm sending the imageUrl. For example: _https://i.imgur.com/0bUSEBX.jpg_

**Comment by gre** [comment]
are you using yarn, then need to `yarn list gl-react` instead.  it should not be empty

ok, so the image URL should work, but i remember someone raised something similar, i'll try to find what could be the cause..

**Comment by chiformihai** [comment]
My bad, I only used npm and it does return 

> └── gl-react@3.8.0

**Comment by gre** [comment]
yeah I think this is an issue that is referencing to the same problem: https://github.com/gre/gl-react/issues/121#issuecomment-307579619

could you make a minimal example that reproduce the problem and share the code to create a new issue in https://github.com/gre/gl-react repo ? thx

**Comment by chiformihai** [comment]
Sure, will do that a little bit later
