### ISSUE TITLE
[Android] Touches on nested View

### ISSUE THREAD

**Issue by shahen94** [ProjectSeptemberInc/gl-react-native#161]
#### library version

```bash
react-native@0.44 (0.45 as well)
gl-react@2.2.10
gl-react-native@2.42.3
```

The nested views are not responding touches correctly when they are in `Surface/AnimatedSurface` . I've tried to use autoDraw but it doesn't help, I tried to find any workaround in native side, but no luck.

Here's an example..

http://www.giphy.com/gifs/l1BgT17uD0Ed1ToAM

I can help you can point the right direction.

**Comment by gre** [comment]
mmh i'm not sure to understand what you are doing but have you tried using `eventsThrough` ? ( https://github.com/ProjectSeptemberInc/gl-react/blob/master/docs/api/Surface.md#props-of-surface )

**Comment by shahen94** [comment]
@gre sure, it doesn't help.

Here's my code

```
import ExtendableImage from 'react-native-extnedable-image';

<View style={styles.container}>
        {this.state.uri && (
          <AnimatedSurface
            visibleContent={true}
            // eventsThrough={true}
            width={width}
            height={height}
          >
            <Earlybird>
              <ExtendableImage
                key={'d'}
                source={{ uri: this.state.uri }} style={{ width, height }}
              />
            </Earlybird>  
          </AnimatedSurface>
        )}
      </View>
```

ExtendableImage is a native solution to achieve Scale/Pan/Zoom for ImageView
https://github.com/shahen94/react-native-extendable-image

But when i wrap my ExtendableImage(or any view with panResponder) into Surface, it updates view only when i release my touches, and not during panning/zooming 🤕 

http://www.giphy.com/gifs/l1BgT17uD0Ed1ToAM

**Comment by shahen94** [comment]
I stuck here 2 days, and can't move forward, i need your help @gre

**Comment by gre** [comment]
oh yeah nevermind you want eventThrough to be false actually, 
so maybe there is a second issue but I think you probably always want to have autoDraw prop because it force the surface to always redraw.

mmh, maybe one thing to try:

https://facebook.github.io/react-native/docs/view.html#pointerevents , see that there is also `box-none` I wonder if setting it instead of `"auto"` here https://github.com/ProjectSeptemberInc/gl-react-native/blob/9c9696ded461c3872eef62cd2a56829652edb077/src/makeSurface.js#L25 fixes the problem


> NB effects over view is very experimental & not so performance because it requires complex code that snapshot the view, inject it into the GPU but this shouldn't "break" to response the touches, mmh..

**Comment by shahen94** [comment]
I've tried that, no luck. I Also tried to call `requestRenderer` every 10ms, to force redraw scene, but again no luck :( . It  updates view only when i release touches.
I didn't tried it on iOS, maybe it work fine, the actual issue is happening on android
