### ISSUE TITLE
Black Screen while running example code on Android

### ISSUE THREAD

**Issue by SuhairZain** [ProjectSeptemberInc/gl-react-native#164]
```
import React, { PureComponent } from 'react';
import { Text, View } from 'react-native';

import GL from 'gl-react';
import { Surface } from 'gl-react-native';

const shaders = GL.Shaders.create({
    helloGL: {
        frag: `
            precision highp float;
            varying vec2 uv;
            uniform float blue;
            void main () {
                gl_FragColor = vec4(uv.x, uv.y, blue, 1.0);
            }
        `
    }
});

const HelloGL = GL.createComponent(
    ({ blue }) =>
        <GL.Node
            shader={shaders.helloGL}
            uniforms={{ blue }}
        />,
    { displayName: "HelloGL" }
);

class FluentLogin extends PureComponent {
    render() {
        return (
            <View>
                <Surface width={300} height={300}>
                    <HelloGL blue={0.5} />
                </Surface>
                <Text>TEST</Text>
            </View>
        );
    }
}

export default FluentLogin;
```

#### library version

```bash
yarn list v0.27.5
├─ gl-react-native@2.47.0
└─ gl-react@2.2.10
```

I'm running the app and this is the result that I get:
![device-2017-09-16-160902](https://user-images.githubusercontent.com/5249794/30511564-66a987fe-9af9-11e7-96d8-a9dcd378e9a5.png)

I'm able to link the library and run the app correctly. There are no issues there.
When running the app, the native Text component seems to be rendered without any issues. And the screen is black even when the Surface is the root component, without any native Views. Could someone kindly help me out?

**Comment by Komeyl94** [comment]
I've got the same problem here
I'm using the same examples but getting black screen!

**Comment by gre** [comment]
which version of React Native are you using? I wonder if it's a regression of recent RN version , because things was working ok a few months ago

**Comment by jcharbo** [comment]
This appears to be due to a change to allow passing a background color.  I don't personally need that feature so I just removed the line of code that passes it (line 125 in src/glcanvas.  You can get my fork here:  https://github.com/thejump/gl-react-native-v2.git
