### ISSUE TITLE
No RNGL in node_modules/gl-react-native

### ISSUE THREAD

**Issue by osdnk** [ProjectSeptemberInc/gl-react-native#165]
```bash
├── gl-react@3.13.0
└── gl-react-native@3.13.0
```

Having installed library via npm, cannot link it to project. I can see no .xcodeproj file in node_modules/gl-react-native.

**Comment by gre** [comment]
you are using the incoming v3, this repo is for the stable v2.

v3 is hosted in https://github.com/gre/gl-react , hopefully will become the "stable" one soon, if you want to use the v3, there is no native code in gl-react-native but you need to install and link react-native-webgl (that the v3 is based on) https://github.com/gre/gl-react/tree/master/packages/gl-react-native

**Comment by matbalazsi** [comment]
I am seeing the same error. Does this solution still apply?

I am using:
"gl-react": "^3.15.0",
"gl-react-native": "^3.15.0",
"react-native-webgl": "^0.8.0",

Do I need V2 of gl-react and gl-react-native?
