### ISSUE TITLE
[IOS] 'React/RCTLog.h' and 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by ghost** [ProjectSeptemberInc/gl-react-native#169]
Hello. Thank you for this great package. I want to use it in my project, but i faced with the following problem:

I use Cocoapods for integration. Here you can see my Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

# The target name is most likely the name of your project.
target 'build_pods' do

  pod 'React', :path => '../../js/node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTLinkingIOS',
  ]
  pod "Yoga", :path => "../../js/node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => '../../js/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../../js/node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../../js/node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNGL', :path => '../../js/node_modules/gl-react-native'
  ...

end
```

And here is part of my package.json dependencies:
```

"dependencies": {
    "gl-react": "^3.11.0",
    "gl-react-native": "^2.47.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.0",
    ...
  },
```
I also tried with gl-react v2.x.x. Result is the same

When i try to build Pods i receive the following errors related to RNGL framework build:
```
'React/RCTLog.h' file not found
'React/RCTBridgeModule.h' file not found
```

Could you please point me what i'm doing wrong and is it possible to integrate this package using one of last react-native versions (for example 0.48.0)?

Thanks in advance

**Comment by ghost** [comment]
Ok, it seems i found solution by myself.

In order to build RNGL framework with react-native v0.48.0 you have to:
1. Open <your_project>/Pods/Target Support Files/RNGL/RNGLxcconfig file
2. Add the following line there: 
`FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/React" "$PODS_CONFIGURATION_BUILD_DIR/Yoga"`

Also gl-react should be 2.x.x version. I have v2.3.1 and it works now

Best regards

**Comment by dharakhatri88** [comment]
I am having the same issue
RCTLog.m file not found

"gl-react": "^2.3.1",
    "gl-react-native": "^2.48.0",
    "react": "16.0.0-alpha.12",
"react-native": "0.47.1",

when i am trying to search <your_project>/Pods/Target Support Files/RNGL/RNGLxcconfig file. i couldnt see it under my folder. what should be wrong? Thanks

**Comment by sebringj** [comment]
@ziks21 not so much

1. On Finder...open <your_project>/Pods/Target Support Files/RNGL/RNGLxcconfig file
2. Add the following line there:
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Private/RNGL" "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/RNGL" `"${PODS_ROOT}/Headers/Public/React"`

For some reason the XCode does some misdirection for the location and doesn't show it directly even if I follow @Fsarmento idea below.

**Comment by Fsarmento** [comment]
Following up on @sebringj  answer, the easiest way to add `${PODS_ROOT}/Headers/Public/React` to Header search paths is to select **Pods** as project, **RNGL** as target from the list of targets. Then, on Build Settings, search for "header search paths" (make sure you have "All" selected in the filter area). Click on the paths and add `${PODS_ROOT}/Headers/Public/React` as a new line.

<img width="1052" alt="screen shot 2018-06-04 at 18 58 37" src="https://user-images.githubusercontent.com/18128610/40933439-5d648c36-6829-11e8-98bf-9c29aa7d5f40.png">
