### ISSUE TITLE
Unable to find "UIView+React.h"

### ISSUE THREAD

**Issue by gmlion** [ProjectSeptemberInc/gl-react-native#170]
gl-react-native@2.47.0

In one of my projects
```
#import "UIView+React.h"
```
was not working in GLCanvas.m for some reason. I fixed changing it to 
```
#import <React/UIView+React.h>
```

I wonder if importing this way is "more solid".

**Comment by gre** [comment]
I think it's because of recent changes in RN, you can send a PR

**Comment by gre** [comment]
assigning myself to do a minor release asap

**Comment by gre** [comment]
not sure if it's still an issue. as gl-react v3 approach, gl-react-native-v2 is less maintained by PR are welcomed
