### ISSUE TITLE
Image is always black

### ISSUE THREAD

**Issue by sbbeez** [ProjectSeptemberInc/gl-react-native#174]
#### library version

```bash
npm ls gl-react gl-react-native # Please run and paste the output of this
```

I have created only two files ``app.js`` and ``saturation.js`` app.js has imported surface, saturation and a slider from respective modules and but the image that has to be render is always black and not even rendering the original image. please check what is happening and put a message in thread.

**Comment by agates4** [comment]
same. this is ridiculous. its like theres no support on the project.

**Comment by gre** [comment]
@agates4 Your message is not helping neither.
need more details, how to reproduce this, which version of the library etc..
examples are working and there are plenty of them for this library. sorry if I don't have time to fix your code.

**Comment by agates4** [comment]
**# Version:**
```
├── react-native@0.50.3 
├── react@16.0.0-alpha.12 
├── gl-react@2.3.1
├── gl-react-hue-rotate@1.1.0 
└── gl-react-native@2.48.0 
```

**# Code:**
```
import { Surface } from "gl-react-native";
import { HueRotate } from 'gl-react-hue-rotate'
```
```
  render() {
    return (
        <Surface width={300} height={250}>
            <HueRotate hue={12}>
                <Image
                    style={{ width: 256, height: 244 }}
                    source={require('../data/CardTemplates/businesscard4.png')}
                />
            </HueRotate>
        </Surface>
    )
}
```

**# Error:**
`undefined is not an object (evaluating 'PropTypes.any')`

I am not using PropTypes in my project, the error must be coming from one of your libraries.

**# Steps to Reproduce:**
- Create a new react-native project
- NPM install gl-react, gl-react-hue-rotate, gl-react-native
- Follow the gl-react-native steps to integrate with Xcode / Android dev environments
- Copy paste the code from above
- Weep

Even when I got the pieces working by removing the proptypes dependency from "react" and changing it to "proptypes", it would just show me the blank screen without an image. 

The image itself is fine. A simple image element is able to display the image without problems. It's when integrating with GL that there becomes an issue.

**Comment by agates4** [comment]
For clarification: after fixing the proptypes problem, the output of the above code results in just a blank screen. 

If I replace the image element in the above code:
```
<Image
         style={{ width: 256, height: 244 }}
         source={require('../data/CardTemplates/businesscard4.png')}
/>
```

With:
`<Text> test </Text>`

The output looks like this:
<img width="406" alt="screen shot 2017-12-26 at 2 17 30 pm" src="https://user-images.githubusercontent.com/2314309/34363145-8b8d4888-ea47-11e7-802e-220bc584d9e0.png">

I don't know why the image element is not working

**Comment by agates4** [comment]
**# More details:**

If I replace the HueRotate code from the library created from
`npm install gl-react-hue-rotate`

With the code implementation of HueRotate described in
[Code Example](https://projectseptemberinc.gitbooks.io/gl-react/content/docs/examples/3.html)

(WHY does the official example have a different code implementation than the official library?)

The output of my code with the image element after adjusting the HueRotate code to be the code from the official example is:
<img width="376" alt="screen shot 2017-12-26 at 2 33 08 pm" src="https://user-images.githubusercontent.com/2314309/34363392-b5259fb8-ea49-11e7-986f-ad8b0e315408.png">


And thus, the black image issue.

**Comment by gre** [comment]
can you see if this would fix it? https://github.com/gre/gl-react-native-v2/issues/66#issuecomment-227383199

**Comment by cwhenderson20** [comment]
I am also having this issue, though I am using v3 (3.13.0). `resolveAssetSource` does not appear to have any difference in whether or not the image loads. Interestingly, images load 100% of the time in the iOS simulator, but maybe only 20% of the time on an actual device.

I've tried using the `preload` setting as an array containing the one image I am loading for the surface, but that also seems to have had no effect.

@gre Please let me know if you need any more information and I will be happy to provide. Thanks for these great libraries.

**Comment by laclys** [comment]
@cwhenderson20  I have same problem on  device( images load 100% of the time in the iOS simulator, but maybe only 20% of the time on an actual device.)

Have you solved this problem?

**Comment by cwhenderson20** [comment]
@laclys Unfortunately I solved the problem by switching to gl-react-native v2.48.0. After switching from v3.13.0, I no longer had this issue (though there are some other issues that came with the switch).

**Comment by sundariragavan** [comment]
@cwhenderson20  In android, black layer added on the image.I'm using "react-native view-shot" for image capturing. Any idea about this issue?

**Comment by aicam** [comment]
I used resizeMode:'contain' and it solved

**Comment by SiddharthRana** [comment]
Did anyone find the solution for this? I am using react-native-gl-image-filters. 
My code looks like : 

<Surface preload={[`data:image/png;base64,${this.state.image.data}`]} onLoad={() => console.log('fired')} width={width} height={width} ref="filtered_image">
                        <ImageFilters {...filter}>
                            <Image style={{ width: width, height: width }} resizeMode='contain'
                                source={this.state.image ? { uri: `data:image/png;base64,${this.state.image.data}` } : require('../../assets/images/icon_no_image.png')} />
                        </ImageFilters>
                    </Surface>

onload is fired instantly. I think i am using preload wrong. I have set the preload to true too, it didnt help. Can anyone please help?
