### ISSUE TITLE
Uniforms for animations, Best Practices

### ISSUE THREAD

**Issue by scisci** [ProjectSeptemberInc/gl-react-native#176]
I want to do a simple plasma animation. This requires have a uniform for time constantly updating and gl rendering as fast as possible.

What is the best practice for this? Do I really just call setState({new Date()}) as fast as possible like in this example: 

https://github.com/gre/gl-react-native-v2/blob/master/example/src/Particles/index.js

It seems like that would have performance side effects regarding re-rendering the vdom.

**Comment by gre** [comment]
yeah i'm afraid that in gl-react-native v2 implementation there are no faster way to do this. gl-react(-native) v3 have more options for this so maybe you want to compare perf of both (i'm not sure if v3 reached yet the same level of perf as v2 tho)

**Comment by scisci** [comment]
Ahh thank you. I'll keep an eye on V3.

**Comment by scisci** [comment]
If autoRedraw is true, could gl-react-native automatically add a time uniform? Would that make sense since it already has a timer going etc.

**Comment by scisci** [comment]
This is an identical request to https://github.com/gre/gl-react-native-v2/issues/99

so closing.
