### ISSUE TITLE
Android Build Faild

### ISSUE THREAD

**Issue by songxiaoliang** [ProjectSeptemberInc/gl-react-native#177]
Execution failed for task ':gl-react-native:downloadJSCHeaders'.

gl-react-native 3.6.0
gl-react 3.6.0

Do not know where the problem, looking forward to the author reply

**Comment by gre** [comment]
this repository is hosting the v2. the error you are referring to is from react-native-webgl. there is an extra thing to add in your build config for Android, see https://github.com/react-community/react-native-webgl#configure-your-react-native-application 

> android/build.gradle: If it's not already there, add gradle-download-task buildscript dependency: classpath 'de.undercouch:gradle-download-task:3.1.2' . If you don't do this, you will likely have :downloadJSCHeaders not working.

**Comment by songxiaoliang** [comment]
@gre thanks, that very great!
