### ISSUE TITLE
How to export the content of GL.View?

### ISSUE THREAD

**Issue by macrostart** [ProjectSeptemberInc/gl-react-native#18]
Is there any way to export the content of a `GL.View` (with the fragment shader applied)?

I'd like to load an image, apply a filter using a glsl fragment shader and export the result. I can't figure out how to do the last part, i.e. exporting. I've checked the gl-react-native documentation and the [GL.View page](https://projectseptemberinc.gitbooks.io/gl-react/content/docs/api/View.html) specifically, but couldn't find anything.

**Comment by gre** [comment]
By export you mean save as an image file?

**Comment by macrostart** [comment]
That would be the easiest, but any other kind of bitmap export would work too.

**Comment by gre** [comment]
This is planned https://github.com/ProjectSeptemberInc/gl-react-native/issues/15 but not yet implemented in gl-react-native

**Comment by macrostart** [comment]
I see. Thanks for the quick answer!
