### ISSUE TITLE
Error: RCTImageLoader.h file not found

### ISSUE THREAD

**Issue by TheDutchCoder** [ProjectSeptemberInc/gl-react-native#180]
When installing this package (React 0.53) Xcode throws an error:
![image](https://user-images.githubusercontent.com/1668207/36270856-dde9df30-124a-11e8-9890-f5e9749bbf0f.png)

neither of the two install methods for iOS work.

#### library version

```bash
some-app@0.1.0 /Users/some-user/projects/some-app
├── gl-react@2.3.1
└── gl-react-native@2.48.0
```

**Comment by Fsarmento** [comment]
Have you tried [this](https://github.com/gre/gl-react-native-v2/issues/129#issuecomment-414279006) solution?
