### ISSUE TITLE
Could not resolve project :RNGL

### ISSUE THREAD

**Issue by wolfag** [ProjectSeptemberInc/gl-react-native#184]
After Gradle sync, I got this error:
->Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :RNGL.
Can you help me to solve this?
Thanks.
#### library version

```bash
-> gl-react-native@3.15.0
-> react@16.4.1
-> react-native@0.56.0
```

**Comment by duquerroy** [comment]
+1

**Comment by IjzerenHein** [comment]
You are trying to install gl-react-native v3. This repo contains the older v2 version.
Try installing `npm install gl-react-native@2.48.0` or choose v3, which is documented here: https://github.com/gre/gl-react

**Comment by duquerroy** [comment]
ok, i'll try it
thanks !
