### ISSUE TITLE
undefined is not an object (evaluatting 'PropTypes.any')

### ISSUE THREAD

**Issue by d2luu** [ProjectSeptemberInc/gl-react-native#189]
#### library version
├─ gl-react-native@2.48.0
├─ gl-react@2.2.0
└─ react-native@0.56.0

After install gl-react & gl-react-native, I just try: 
```
import GL from 'gl-react';
```
but I got error:
 
<img width="337" alt="screen shot 2018-10-05 at 1 30 28 pm" src="https://user-images.githubusercontent.com/14581772/46516595-78fff700-c8a5-11e8-91b9-e1d7e0646290.png">

Can you help me to solve this?
Thanks.

**Comment by Duckers** [comment]
Same problem here, seems to not work with more recent React versions

**Comment by giginkrishnan** [comment]
I got the same issue, any solution on this

**Comment by azharrizkip** [comment]
I got the same issue, any solution? cause i really need it

**Comment by giginkrishnan** [comment]
> I got the same issue, any solution? cause i really need it

 think this will help you,

install  "prop-types": "^15.6.2", to your project
and add a peer dependency prop-types in gl-react-native
then replace the code with propTypes

**Comment by azharrizkip** [comment]
> > I got the same issue, any solution? cause i really need it
> 
> think this will help you,
> 
> install "prop-types": "^15.6.2", to your project
> and add a peer dependency prop-types in gl-react-native
> then replace the code with propTypes

any example or screenshot?? cause I've installed prop-types to my project, and then don't know where should I put it to gl-react-native

**Comment by shamilsun** [comment]
do you solved this issue ? 

same problem

**Comment by giginkrishnan** [comment]
Ya , but I removed this feature from my project

**Comment by giginkrishnan** [comment]
install prop-types

<img width="335" alt="screen shot 2018-11-12 at 3 36 53 pm" src="https://user-images.githubusercontent.com/18523239/48376563-e8c98480-e690-11e8-8f2d-0f3edad16a9d.png">

Add a peer dependency in **gl-react** package.json

Open - gl-react/lib/Uniform.js

<img width="344" alt="screen shot 2018-11-12 at 3 37 09 pm" src="https://user-images.githubusercontent.com/18523239/48376595-ff6fdb80-e690-11e8-97cb-5e516483a775.png">

replace  React PropTypes with new PropTypes

**Comment by danielreuterwall** [comment]
It's also fixed in gl-react 2.3.1 so no need to change the source yourself.

**Comment by numandev1** [comment]
add ^ sign infront of version 
`"gl-react": "^2.2.8"`
