### ISSUE TITLE
Could not find @ReactModule on app start

### ISSUE THREAD

**Issue by southerton81** [ProjectSeptemberInc/gl-react-native#193]
Could not find @ReactModule annotation in com.projectseptember.RNGL.RNGLContext
getNameFromAnnotation
    CatalystInstanceImpl.java:444
getNativeModule
    CatalystInstanceImpl.java:433
getNativeModule
    ReactContext.java:119
<init>
    GLCanvas.java:84
createViewInstance
    GLCanvasManager.java:95
createViewInstance
    GLCanvasManager.java:22
createView
    ViewManager.java:45
createView
    NativeViewHierarchyManager.java:260
execute
    UIViewOperationQueue.java:200
run
    UIViewOperationQueue.java:911
flushPendingBatches
    UIViewOperationQueue.java:1025
access$2600
    UIViewOperationQueue.java:46
doFrameGuarded
    UIViewOperationQueue.java:1085
doFrame
    GuardedFrameCallback.java:29
doFrame
    ReactChoreographer.java:166
doFrame
    ChoreographerCompat.java:110
run
    Choreographer.java:869
doCallbacks
    Choreographer.java:683
doFrame
    Choreographer.java:616
run
    Choreographer.java:857
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
loop
    Looper.java:154
main
    ActivityThread.java:6077
invoke
    Method.java
run
    ZygoteInit.java:866
main
    ZygoteInit.java:756

#### library version
├── gl-react@2.3.1 
└── gl-react-native@2.57.0 

react-native: 0.58.3

**Comment by southerton81** [comment]
Added pull request #194 that fixes this issue.

**Comment by jeroenpg** [comment]
I tried out the PR of @southerton81 and it does resolve the issue. 👍 

See https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#0580 for more info

**Comment by viewpnt1** [comment]
when is this going to be merged?

**Comment by numandev1** [comment]
how can i install this commit. because it is not working on package.json
`"gl-react-native":"git://github.com/gre/gl-react-native-v2.git#10d3dce593080301dc12e467cd5e1c3d22995167"`

**Comment by numandev1** [comment]
will you please reply me?

**Comment by numandev1** [comment]
@southerton81 are you there?

**Comment by SiddharthRana** [comment]
I am getting the same error. Any resolution?
