### ISSUE TITLE
unable to find module for uimanager (lazilyloadIfNeccessary)

### ISSUE THREAD

**Issue by numandev1** [ProjectSeptemberInc/gl-react-native#197]
in react native 0.58 they added lazilyloadIfNeccessary and remove uimanager. but your library is using uimanger. I face this error when I reload app like cmd+r. Therefore I am facing an error that has attached below. please update your library for new versions of react native

you can see changelog for react native 0.58
https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#058

![Screenshot 2019-04-19 at 2 43 48 AM](https://user-images.githubusercontent.com/36044436/56393446-e4138880-624d-11e9-8446-59593a717c78.png)

#### library version

```bash
├── gl-react@2.3.1
├── gl-react-native@2.57.0
```

**Comment by nederev** [comment]
Hey @nomi9995 

Check @karanjthakkar's  solution from https://github.com/facebook/react-native/issues/23235 worked for me like a magic

**Comment by kevinvangelder** [comment]
This issue is a React Native issue, unrelated to this library.
