### ISSUE TITLE
Please release a new version that works with react-native 0.58

### ISSUE THREAD

**Issue by aromahn** [ProjectSeptemberInc/gl-react-native#198]
Would you please create a new release?
That would be really great. You code already contains all changes but what I need is not released.

Cause: 
react-native framework from version 0.58 requires @ReactModule annotation for native modules.
You already fixed that in the repository but did not create a release.

Fix:
You already fixed and closed the issue: "Added @ReactModule annotation for react-native 0.58"
https://github.com/gre/gl-react-native-v2/commit/2d5891e122734756d5a2befe93fdccbf2cbad3d4

#### library version
├── gl-react@2.3.1 
├── gl-react-native@2.57.0 
└─┬ react-native-image-cropper@0.4.5
  ├── gl-react@2.3.1 
  └── gl-react-native@2.57.0

**Comment by numandev1** [comment]
@aromahn you can add this line to package.json. it will work
`"gl-react-native": "git://github.com/nomi9995/gl-react-native-v2.git#2d5891e122734756d5a2befe93fdccbf2cbad3d4"`

and you can also use in peer dependency it will work for you because you are using two tie gl-react-native

**Comment by aromahn** [comment]
@nomi9995 Thank you very much for answering so quickly!
I could successfully build and test the app.

Is there still a chance for a new release?

**Comment by numandev1** [comment]
@aromahn I don't know
