### ISSUE TITLE
support for Array uniforms

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react-native#26]
no array types are currently implemented.

It's quite easy to implement but very verbose.. It would be great if we could define some macros to generate them (to also simplify existing code)

this will be implemented with accepting a flatten array, like in [gl-shader](https://github.com/stackgl/gl-shader) implem.

> For instance if you have a `vec2 foo[3]`, you should be able to send a array of 6 numbers

**Comment by miklosme** [comment]
Hello, any news on this? This would be pretty useful feature to me currently. Would this js [preprocessor](https://github.com/jsoverson/preprocess) help?
- `@echo VAR`
  This will include the environment variable VAR into your source
- `@foreach $VAR in ARR` / `@endfor`
  This will repeat the enclosed block for each value in the Array or Object in ARR. Each value in ARR can be interpolated into the resulting content with $VAR.
- `@exec FUNCTION([param1, param2...])`
  This will execute the environment FUNCTION with its parameters and echo the result into your source. The parameter could be a string or a reference to another environment variable.

**Comment by gre** [comment]
This needs to be implemented on native side though (objc / java). Maybe
both have some sort of macros way. Otherwise we'll just copy paste all the
required code

Le lun. 6 juin 2016 17:57, Miklós Megyes notifications@github.com a
écrit :

**Comment by peterschmiz** [comment]
Hi,

This would be really nice to have in gl-react-native!
Any chance that a good hearted developer will do that macro or change?

**Comment by gre** [comment]
this is implemented in https://github.com/ProjectSeptemberInc/gl-react-native/releases/tag/v2.27.0 release
