### ISSUE TITLE
Fragment shader examples

### ISSUE THREAD

**Issue by gundam-wing** [ProjectSeptemberInc/gl-react-native#29]
I'm just wondering if anyone can post some more examples of interesting fragment shaders?

**Comment by gre** [comment]
how interesting?

Here are some sites:
Demos: http://glslsandbox.com / http://shadertoy.com
Transitions: http://transitions.glsl.io/

**Comment by gundam-wing** [comment]
Whatever you've got! Just something more than the basic hue rotate type examples listed currently. I'm mainly interested in post-processing effects.

**Comment by gre** [comment]
there are tons of github repositories that have fragment shaders (with some search on Github). just a random one: https://github.com/tangrams/ProceduralTextures , you can also search on google.

**Comment by gre** [comment]
please share you discoveries.

I've opened a Wiki at https://github.com/ProjectSeptemberInc/gl-react/wiki/Great-Resources (maybe something similar exist somewhere on the internet!)
**feel free to edit this wiki!**

Thanks
