### ISSUE TITLE
[iOS] integrate with new way of using image source

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react-native#42]
https://github.com/facebook/react-native/commit/b67229485834113674b25bda193a7426bf44cfc8

this is bleeding edge, but not to forget about it when it is released

**Comment by gre** [comment]
looks promising but waiting this to be more consistent with Android version

**Comment by gre** [comment]
related #5

**Comment by nicklockwood** [comment]
cc: @dmmiller

**Comment by gre** [comment]
fixed with https://github.com/ProjectSeptemberInc/gl-react-native/commit/6fc8611fcb2ce45251fdc329a51d5a793c7f82e4 – will need to see to impl it on Android
