### ISSUE TITLE
capture method in GLCanvasManager.m

### ISSUE THREAD

**Issue by davidsims9t** [ProjectSeptemberInc/gl-react-native#43]
Hello,

I'm using React Native v0.15 and I found that this library doesn't seem to be compatible with this version yet (I'm guessing). I got an error originally saying that the addUIBlock block wasn't expecting a NSDictionary to be passed, so I looked at how this was being handled in React Native and found it should be changed to RCTSparseArray instead of an NSDictionary. That seemed to fix that error, but now I'm getting an error that UIView expects a dictionary to be passed in.

Thanks in advance!

**Comment by davidsims9t** [comment]
Never mind it seems all I need to do was include "RCTSparseArray.h".

**Comment by gre** [comment]
yeah react-native introduced a breaking change in 0.16.

gl-react-native 2.0.x should work with < 0.16
gl-react-native 2.1.x should work with >= 0.16

**Comment by davidsims9t** [comment]
Yeah I got it to work in 0.15 by just changing NSDictionary in the ui.bridge.manager block to RCTSparseArray. Is that the breaking change?
