### ISSUE TITLE
createSurface not a function

### ISSUE THREAD

**Issue by davidsims9t** [ProjectSeptemberInc/gl-react-native#44]
![image](https://cloud.githubusercontent.com/assets/6386314/11735277/4974df9e-9f74-11e5-94a3-feb37257cc42.png)

**Comment by gre** [comment]
can you show me how you use/import createSurface ?

**Comment by davidsims9t** [comment]
I'm just importing the library using: import GL from 'gl-react/react-native' followed by: import { Surface } from 'gl-react-native'

**Comment by gre** [comment]
which versions of gl-react and gl-react-native ?

**Comment by davidsims9t** [comment]
For gl-react it's 2.0.2 and for gl-react-native it's 2.1.3.

**Comment by gre** [comment]
weird, it should work.
I've just re-checked & https://github.com/gre/gl-react-image-effects is working on iOS, with the same lib versions.

the error makes me think your gl-react local version / files is somehow wrong. 

Can you check that these 2 commands show some createSurface occurences:
- `cat node_modules/gl-react/lib/index.js | grep createSurface`
- `cat node_modules/gl-react-native/src/Surface.js | grep createSurface`

**Comment by davidsims9t** [comment]
Ah ok so I think it was an issue with the import statements I was using because I was able to get it to work with require() statements. Also I didn't have require('gl-react-native') at the top of my script. Everything it working great now. Thanks for the help!
