### ISSUE TITLE
Bizarre React Native Module Behavior

### ISSUE THREAD

**Issue by lambdahands** [ProjectSeptemberInc/gl-react-native#51]
I'm having really streaky results importing modules in React Native.

This for example gives me an error:

``` js
require('gl-react/react-native');
import React from 'react-native';
import { Surface } from 'gl-react-native';
// => gl-react: React instance not available at runtime. Please read instructions.
```

However if I define a blank module,

``` js
// emptyModule.js
require('gl-react/react-native');
import React from 'react-native';
```

and import it _specifically_ between the React and `gl-react-native` import,

``` js
require('gl-react/react-native');
import React from 'react-native';
import _ from 'emptyModule.js';
import { Surface } from 'gl-react-native';
```

everything compiles and runs without error.

Am I missing something in the docs? I've had a lot of trouble moving modules around because of unpredictable behavior. As long as I include _some_ module that requires `gl-react/react-native`, the error goes away, but I end up having to import a blank module across all of my files.

**Comment by gre** [comment]
If you use es6 import you also need to use es6 import instead of the
require.

Like:

import __ from "gl-react/react-native";

This is because import es6 synthax are treated before require in Babel
Le 22 déc. 2015 3:49 AM, "Philip Joseph" notifications@github.com a
écrit :

**Comment by lambdahands** [comment]
Ah, thank you for the clarification! Totally makes sense now. :smile:

**Comment by gre** [comment]
I'll add a better error message
