### ISSUE TITLE
[Android] Performance passing rasterized React Native views as uniforms

### ISSUE THREAD

**Issue by gr4yscale** [ProjectSeptemberInc/gl-react-native#61]
I'm not sure if the slowness I'm seeing on Android is my code or if it's not. I've tried profiling with systrace and will post the results below. 

Passing just 1 single react native view in as a texture to a shader runs very fast on iOS with my 6+ (>40fps always), but with a Samsung Galaxy A5 it runs < 10fps

Using the same technique as demonstrated in the AdvancedEffects Example.

```
render () {
  const { value } = this.state;
  const { width, height, children } = this.props;

  return (
  <Surface
      width={width} height={height}
      pixelRatio={2}
      ref="rgbshift"
      style={{position:'absolute', width, height, top:0, left: 0}}
  >
      <GL.Node
          shader={shaders.rgbshift}
          uniforms={{ tInput: children, time: value}}
      />
  </Surface>
  )
}
```

Profiling with systrace (per instructions here: https://facebook.github.io/react-native/docs/android-ui-performance.html) shows a lot of time on 'com.havit' (my package), but I suppose since I don't have markers in place there isn't anything specific. I'm doing nothing special and have tested with shouldComponentUpdate() returning false.

Any ideas for how to go about digging into this, and could you please just confirm that the slowness is indeed my code and not this fantastic libraries by taking a quick peek at the screenshots and systrace generated html (it's zipped to get around github filetype limitations)?

<img width="822" alt="screen shot 2016-01-25 at 11 20 13" src="https://cloud.githubusercontent.com/assets/1342396/12549729/1a32da40-c357-11e5-9ffe-41c12577a29a.png">

<img width="1612" alt="screen shot 2016-01-25 at 11 20 47" src="https://cloud.githubusercontent.com/assets/1342396/12549732/1e52a3e4-c357-11e5-86da-4d5c5b893078.png">

[trace.html.zip](https://github.com/ProjectSeptemberInc/gl-react-native/files/103123/trace.html.zip)

**Comment by gre** [comment]
there might be a bug. we need to investigate. BTW do you know how to add profile markers in ReactNative systrace on Android? on iOS it was possible, but on Android I couldn't find a way (maybe systrace is part of Android?) . It would be neat if we could add them.

This would help to know more precisely from where this comes, but it is likely related to rasterization, although it's weird you still have slowness when doing shouldUpdate={false} .. It is likely there is a bug in the lib where we always re-rasterize and we shouldn't.

I'll take a look later in the week or next weekend. otherwise feel free to investigate / provide PRs :)

Thanks

**Comment by gr4yscale** [comment]
@gre Sorry for the late reply, busy week! I think that the way they've been added in the repo (such as the contribution @ptmt made) is the correct way to add profile markers, but I'm not seeing any React Native code when running Android's systrace tool. In the screenshot I sent it doesn't have the threads which are mentioned in [the guide on the React Native site](https://facebook.github.io/react-native/docs/android-ui-performance.html)

I meant to link you to [this github issue (5551)](https://github.com/facebook/react-native/issues/5551) I created on the RN repo recently...was waiting for a response, but nothing so far... I went down a long path that day trying to understand what is the current state of profiling tools with React Native. This issue was of course related to iOS, but the replies could be helpful regardless.

I think it's crucial to be able to profile our code so will keep investigating this.

As far as the performance issue here goes, I've looked at the iOS and Android implementations both - for me the iOS impl is much easier to read and seems simplified, although they're obviously quite similar. Can you share if there are any specific differences in how the Android side works vs iOS to help me give some direction to go off of for testing changes? Again, I'm not great with GL, but still know a thing or two!

Thanks for your work on this stuff, it's quite awesome!

**Comment by gre** [comment]
I don't have a good knowledge on the Android side, but when trying to basically port the iOS impl to Android I was facing some difficulty like the fact it doesn't seem possible (AFAIK) to share objects across different GLSurfaceView. So the main difference is that iOS is able to share framebuffers and shaders across multiple Surface but the Android implementation is not (like the web implementation actually, one canvas, one context).

**Comment by gre** [comment]
view rasterization on Android is definitely a bottleneck (which is totally not in iOS impl). I can't find a way to improve this perf. But I should introduce this https://github.com/ProjectSeptemberInc/gl-react/issues/53

**Comment by robclouth** [comment]
@gre [here](https://github.com/ArtemBogush/AndroidViewToGLRendering) is a repo showing how to cheaply render arbitrary views to GL textures on android. Maybe you're already doing this though. To be honest I've haven't dug through your code.

**Comment by gre** [comment]
it looks like it's implemented specifically for WebView https://github.com/ArtemBogush/AndroidViewToGLRendering/blob/master/app/src/main/java/com/self/viewtoglrendering/GLWebView.java

I think there are definitely ways to improve performance of this, but I don't have enough experience in native Android on this subject.
