### ISSUE TITLE
performance on blurring

### ISSUE THREAD

**Issue by genxstylez** [ProjectSeptemberInc/gl-react-native#63]
When I use a 4-pass blur in my app, before the image loads the view shows black.

please help

``` js
let dimension = Dimensions.get('window')
<Surface width={dimension.width} height={dimension.height} style={styles.backgroundImage} preload>
  <Blur minBlur={0} maxBlur={3} blurMap={'http://i.imgur.com/0PkQEk1.png'} offset={[10, 0]}>
    http://cdn12.lbstatic.nu/files/looks/large/2015/12/30/4789931_deichmann-with-skirt.jpg?1451472058
  </Blur>
</Surface>
```

**Comment by gre** [comment]
put an `opaque={false}` on the surface and it will be transparent. black is the default color otherwise.

**Comment by genxstylez** [comment]
anyway to speed up the performance?

**Comment by genxstylez** [comment]
also, when I blur the image with a scroll event, the UI frame rate is very poor, mostly 0~5 fps

**Comment by gre** [comment]
see https://github.com/ProjectSeptemberInc/gl-react-native/issues/62#issuecomment-176053287

**Comment by genxstylez** [comment]
@gre one more question, so are there anyways to speed up `<Surface />` rendering?

**Comment by gre** [comment]
it's already being discussed in #62 !

**Comment by genxstylez** [comment]
I mean the initial loading of surface, not when a state or prop change

**Comment by gre** [comment]
the initial Surface rendering should be ~ as fast as an update. If you have long time during the rendering it might be because you are waiting an image to load?

It's hard to me understand what's wrong in your case, can you try to use systrace to profile and see the timeline on what's happening?

**Comment by genxstylez** [comment]
Will do. Thx
