### ISSUE TITLE
Suggestion for install instructions on Android

### ISSUE THREAD

**Issue by AlexDM0** [ProjectSeptemberInc/gl-react-native#65]
Hi, I was trying to add this package to a fresh project and this part:

in your MainActivity (or equivalent):
import com.projectseptember.RNGL.RNGLPackage;
...
mReactInstanceManager = ReactInstanceManager.builder()
    .setApplication(getApplication())
    ...
    .addPackage(new MainReactPackage())
    .addPackage(new RNGLPackage())
    ...
    .build();

Was nowhere to be found and I didnt know what to do with it. Turns out I did have this:

```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage()
      );
    }
```

So I changed it to this:

```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(), new RNGLPackage()
      );
    }
```

and it recognised the package. 

I'd like to suggest to add a bit more information to the setup guide :)

Thanks for the project!

**Comment by gre** [comment]
yeah, this doc is outdated, this recently changed in a recent RN version.
Feel free to submit a PR :)

**Comment by AlexDM0** [comment]
Sure, I'll make a pull soon. I'm not that experienced with Android or ReactNative so I'm not sure I can cover all cases.

Cheers

**Comment by gre** [comment]
Thanks
