### ISSUE TITLE
[Android] Rounded Corners

### ISSUE THREAD

**Issue by AlexDM0** [ProjectSeptemberInc/gl-react-native#67]
Hi,

Sorry for the inflow of issues! I'm trying to get  an image that is being created by gl to have rounded corners (borderRadius: 50, width&height:100). It ignores the style on the shader, surface or encompassing view:

```
<View style={styles.rounded}>
  <Surface width={100} height={100} style={styles.rounded}>
    <Saturation
      factor={0.5}
      image={{ uri: "http://i.imgur.com/iPKTONG.jpg" }}
      style={styles.rounded}
    />
 </Surface>
</View>
```

with:

```
const styles = StyleSheet.create({
  rounded: {
    width: 100,
    height: 100,
    borderRadius: 50,
    overflow:'hidden'
  }
});
```

Is this possible or do I need to do everything offscreen, save the image and show it later?

Cheers

**Comment by AlexDM0** [comment]
I tried saving the images to disk (using RNFS and surface captureFrame) but if I use the file URL i get from the promise and put it in an Image source={uri: fileURL} all I get is a black space. FSread of the url gives me the image blob but I cant use the blob in an Image..

Any ideas?

EDIT: still running the andoid emulator. Should this just work in iOS?

**Comment by gre** [comment]
seems to be a bug with Android and i'm not sure what we can do about it.

**the borderRadius works on View but does not seem to work when using with a GLSurfaceView** (Android under the hood implementation).

I'm pretty sure it's a bug with how the "z index"/masking works on GLSurfaceView.. this might be related to #60 as well

**Showcase in Tests**

``` js
<Surface style={{ borderRadius: 50 }} width={debugSize} height={debugSize}>
  <HelloGL />
</Surface>
```

<img width="853" alt="screen shot 2016-03-06 at 14 21 38" src="https://cloud.githubusercontent.com/assets/211411/13554445/3e5ba106-e3a8-11e5-8ab6-5ff14b5f8983.png">

---

**Workaround:**

Implementing the crop in GL

``` html
<Surface>
  <CircleCrop>
    <HelloGL />
  </CircleCrop>
</Surface>
```

``` js
import React from "react";
import GL from "gl-react";
const shaders = GL.Shaders.create({
  circleCrop: {
    frag: `
precision highp float;
varying vec2 uv;
uniform sampler2D t;
void main () {
  gl_FragColor = mix(
    texture2D(t, uv),
    vec4(0.0),
    step(0.5, distance(uv, vec2(0.5))));
}`
  }
});
const CircleCrop = GL.createComponent(
  ({ children: t }) =>
  <GL.Node shader={shaders.circleCrop} uniforms={{ t }} />);
```

**Comment by AlexDM0** [comment]
Thanks for the workaround! You've been a great help so far! Is issue with the file system is the same underlying cause as #66?

Cheers

**Comment by gre** [comment]
maybe, although I'm not sure if fileURL is supported (is it on iOS?). Eventually if we figure out how to implement #66 according to Image#source spec, we should have the same behavior

**Comment by AlexDM0** [comment]
I was going by the documentation here: https://projectseptemberinc.gitbooks.io/gl-react/content/docs/api/Surface.html

which states:
Implementation have other specific options:
in gl-react-native, format: "file" allows to save to a file. You also need to provide a filePath String (you should use react-native-fs to knows directory paths). The promise result will be a file://... url that you can use in <Image source= />.

Am I reading this wrong?

Thanks!

**Comment by gre** [comment]
Is the image saved?

file:/// should work for saving the image, but i'm not sure it works when piping back to the uniform texture on Android, there is probably a bug there, and it should be addressed when fixing #66 .

**Comment by AlexDM0** [comment]
If I use the rnfs module to read the file I do get a blob which I assume is the image so I do think it's saved. If #66 fixes it that would be great!

**Comment by AlexDM0** [comment]
Hi,

I've tried the circlecrop and it doesnt seem to make the rest transparent.
![example](https://cloud.githubusercontent.com/assets/5363277/13848243/3786ba3a-ec51-11e5-909f-0bc2967b4f9c.png)

I'm not a star in openGL shading so it could be an easy fix. Any ideas?

EDIT: this is the exact same code on iOS and Android.

```
 <View style={{borderWidth:20, borderColor:'#a0a0a0', borderRadius:200}}>
  <Surface width={300} height={300} borderRadius={150}>
    <CircleCrop>
        <Saturation r={colors.red.r/255} g={colors.red.g/255} b={colors.red.b/255} factor={0.5} image={this.image} />
    </CircleCrop>
  </Surface>
</View>
```

Regards

**Comment by gre** [comment]
you need to do: `backgroundColor="transparent"`   on Surface

**Comment by AlexDM0** [comment]
Hi, thanks for the reply! I'm afraid it doesnt work though.. It seems backgroundColor does not work (with or without circleCrop)
![example2](https://cloud.githubusercontent.com/assets/5363277/13848709/558b48c8-ec53-11e5-8d5a-264873de44aa.png)

Hope this helps:
Shaders:

```

const shaders = GL.Shaders.create({
  saturation: {
    frag: `
precision highp float;
varying vec2 uv;
uniform sampler2D image;
uniform float factor;
uniform float r;
uniform float g;
uniform float b;

void main () {
  vec4 c = texture2D(image, uv);
  // Algorithm from Chapter 16 of OpenGL Shading Language
  const vec3 W = vec3(0.2125, 0.7154, 0.0721);
  vec3 color = vec3(r,g,b);
  vec3 gray = vec3(dot(c.rgb, W));
  vec3 res = mix(gray * color, color, factor);
  gl_FragColor = vec4(res,0.3);
}
    `
  },
  circleCrop: {
    frag: `
precision highp float;
varying vec2 uv;
uniform sampler2D t;
void main () {
  gl_FragColor = mix(
    texture2D(t, uv),
    vec4(0.0),
    step(0.5, distance(uv, vec2(0.5))));
}`
  }
});
```

code in renderer:

```
<View style={{borderWidth:20, borderColor:'#ff0000', borderRadius:200, backgroundColor:'#00ff00'}}> 
  <Surface width={300} height={300} backgroundColor="#0000ff">
    <CircleCrop>
      <Saturation r={colors.red.r/255} g={colors.red.g/255} b={colors.red.b/255} factor={0.5} image={this.image} />
    </CircleCrop>
  </Surface>
</View>
```

To check if its was the transparency I changed it into blue and green. You can see the results in the image. Any ideas? Sorry for the hassle!

EDIT: using react native 0.21

Regards

**Comment by gre** [comment]
oh, so it only doesn't work on Android?

**Comment by AlexDM0** [comment]
Well, in iOS the background shade is green, which is from the View, not the surface (since thats blue). The Android version seems stuck at black.

Regards

**Comment by gre** [comment]
at the moment I think backgroundColor is only supported for setting to "transparent" in gl-react-native (to disable the default opaqueness). will fix later.

maybe there is a bug in android for support of this then.

if you can investigate / provide a PR, it would be the best, otherwise, will have to wait at least this weekend.

**Comment by AlexDM0** [comment]
I'm afraid I wouldn't know where to start in this regard. On the upside, local images work now :).

Regards

**Comment by gre** [comment]
sorry i'm confused. local image works, not distant? we discussed a lot of things there. would you mind summarizing what are the bugs in an atomic / precise way? thanks :)

**Comment by AlexDM0** [comment]
Hi sorry, I was referring to the other outstanding issue where require of local files didnt work in a surface. This can be solved with the resolveAssetSource method. Shouldnt have mixed them in the comment.

This issue here is exactly as described in the comment with the shader code in it. If I have a Surface, on Android the borderRadius does not work. Your circleCrop works for the image, except the black outline cannot be removed (the square). This eventually boils down that backgroundColor: "transparent" does not work on Android. On iOS it's not required but I also cannot get it to do anything (like if I remove the borderRadii, the view background color is shown).

My goal is to have the android app to look the same as the iOS one: a red image with a border, no square.

Sorry for the mixup.

**Comment by peterschmiz** [comment]
Hi,

I have the same issue with backgroundColor="transparent" on Android. Its simlply black.
Not sure if it has something to do with RN or with gl-react-native.

Anyway, can you give an update on this bug?

**Comment by peterschmiz** [comment]
After a little further investigation (unfortunatelly I'm not an Android developer) changing line 92-93 in the file GLCanvas.java:

```
    getHolder().setFormat(PixelFormat.TRANSLUCENT);
    setZOrderOnTop(true);
```

it works.

I have a fear, that setZOrderOnTop with value true will cause other issues (e.g. overlay over a GL content etc.). Still, maybe this helps or someone can provide a PR with updated Android code.

**Comment by gre** [comment]
there used to be this code

``` js
setZOrderOnTop(true);
```

but there where this bug: https://github.com/ProjectSeptemberInc/gl-react-native/pull/59

not sure how to reconciliate both problems :s

**Comment by peterschmiz** [comment]
Uhh, sorry to hear that :(
I hope someone can clear this up and solve both issues.
