### ISSUE TITLE
[iOS] _addShader dead code 

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react-native#71]
https://twitter.com/snikhilesh/status/707406939592916992

looks like it's dead code

wondering if we can somehow do code coverage, sounds tricky with our 3 langs JS & ObjC & Java :D

**Comment by macrostart** [comment]
Not sure if `GLFBO.m`'s `initRenderBuffer` is called from anywhere else too ([link](https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/ios/GLFBO.m#L50-L59)).
