### ISSUE TITLE
[iOS] captureFrame not working on the device, works in Simulator

### ISSUE THREAD

**Issue by macrostart** [ProjectSeptemberInc/gl-react-native#75]
I've tried to use `captureFrame` and I've discovered that it doesn't work on my iOS device (iPhone 5, tested on iOS 8 & iOS 9). The output is:
- For `{type: 'jpg', format: 'file'}`: white image (file).
- For `{type: 'png', format: 'file'}`: transparent png (file).
- For `{type: 'png', format: 'base64'}`: transparent png (encoded in a base64 string).

I've tested all of these on the Simulator (iOS 8, iOS 9) and they work fine. The frame is saved as an jpg file / png file / base64 string, all as expected.

Could someone with access to another device verify whether the `captureFrame` works?

---

Versions of my libraries are as follows; react-native: 0.23.1, gl-react-native: 2.22.0, gl-react: 2.2.0.

**Comment by macrostart** [comment]
I've found a slightly old SO thread which suggests that GLKView's snapshot (currently being used in captureFrame) doesn't work on selected iOS devices: http://stackoverflow.com/questions/26894485/snapshot-fails-on-some-ios-devices .

**Comment by macrostart** [comment]
Tried some workarounds for this issue, posting them here, maybe they'll be helpful to others:
- I've tried using code from this SO thread: http://stackoverflow.com/questions/9550297/faster-alternative-to-glreadpixels-in-iphone-opengl-es-2-0/9704392#9704392 , but it didn't work either on my iPhone 5 (same results as `[self snapshot]` ).
- I ended up using react-native-view-snapshot plugin: https://github.com/jsierles/react-native-view-snapshot . It's not the best solution from the point of view of performance, but it works in my case.

**Comment by gre** [comment]
do you know if there is a way to feature detect the problem, and switch based on this?

**Comment by superandrew213** [comment]
@macrostart are you still having this issue with the latest version?
