### ISSUE TITLE
Can you support Pixi.js?

### ISSUE THREAD

**Issue by jdnichollsc** [ProjectSeptemberInc/gl-react-native#76]
Hi guys!

Do you want support **Pixi.js** to use **WebGL/Canvas** easily?

Regards, Nicholls

**Comment by macrostart** [comment]
I remember a discussion that went in a similar direction, you might want to check it out: https://github.com/ProjectSeptemberInc/gl-react-native/issues/13 .

**Comment by gre** [comment]
yes. also answered it https://github.com/ProjectSeptemberInc/gl-react/issues/62#issuecomment-210604236
