### ISSUE TITLE
[android]Requiring unknown module "gl-react"

### ISSUE THREAD

**Issue by leoabacade** [ProjectSeptemberInc/gl-react-native#78]
I am getting below error message after npm i --save gl-react-native on my react-native android project
android version : Nexus 6 - 5.0.1
react-native version : 0.20.0

Saturation.js :
`import React from "react";`
`import GL from "gl-react";`

`const shaders = GL.Shaders.create({`
 `saturation: {`
`frag:``
`precision highp float;`
`varying vec2 uv;`
`uniform sampler2D image;`
`uniform float factor;`

`void main () {`
  `vec4 c = texture2D(image, uv);`
`// Algorithm from Chapter 16 of OpenGL Shading Language`
`const vec3 W = vec3(0.2125, 0.7154, 0.0721);`
`gl_FragColor = vec4(mix(vec3(dot(c.rgb, W)), c.rgb, factor), c.a);`
`}`
`}`
`});`
`module.exports = GL.createComponent(`
`({ factor, image, ...rest }) =>`
`<GL.Node`
`{...rest}`
`shader={shaders.saturation}`
`uniforms={{ factor, image }}`
`/>,`
`{ displayName: "Saturation" });``

![13105901_10153687867548163_1399721059_o png](https://cloud.githubusercontent.com/assets/2664504/14921289/17dc65a6-0e64-11e6-9bb9-53a28b0f73eb.jpeg)

**Comment by gre** [comment]
as the error said, you also need to install  `gl-react` to use `gl-react-native` ,
it's a peer dependency.

> `gl-react` is needed both by gl-react-native and gl-react-dom, also third party lib (like gl-react-blur) will dep on `gl-react`, so I've made that end user have to explicitly depend on it so there is no duplicate instances.

**Comment by leoabacade** [comment]
I did, that's why I have no idea why it shows the error

npm i --save gl-react-native did install these three components : 
<img width="527" alt="screen shot 2016-04-30 at 12 31 14 am" src="https://cloud.githubusercontent.com/assets/2664504/14922580/f9907edc-0e6a-11e6-810e-24aec3e74838.png">

the error still pops up after I explicitly run npm i --save gl-react to install gl-react

**Comment by gre** [comment]
that's weird. can you tell me which  gl-react and gl-react-native version ?

**Comment by leoabacade** [comment]
"name": "gl-react",
  "version": "2.2.0",
and
 "name": "gl-react-native",
  "version": "2.24.0",

<img width="254" alt="screen shot 2016-04-30 at 12 44 30 am" src="https://cloud.githubusercontent.com/assets/2664504/14922903/c24c980a-0e6c-11e6-838a-684dcca8ffff.png">
<img width="238" alt="screen shot 2016-04-30 at 12 44 06 am" src="https://cloud.githubusercontent.com/assets/2664504/14922907/c6d00ee8-0e6c-11e6-842b-568f3ae97a22.png">

**Comment by leoabacade** [comment]
issue disappeared after upgrade it to  "react-native": "^0.24.1"
<img width="249" alt="screen shot 2016-05-03 at 1 01 53 pm" src="https://cloud.githubusercontent.com/assets/2664504/14975004/5a559fc4-112f-11e6-88cf-eb5aad659a9f.png">

thanks, it is a nice component.
