### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react-native#8]
(just creating this placeholder issue for now)

If anyone want to port an Android implementation, feel free.
Otherwise we will eventually go there ;)

**Comment by pilwon** [comment]
:+1:

**Comment by sulliwane** [comment]
:+1:

**Comment by gre** [comment]
Fixed now :) Android version is almost feature complete https://github.com/ProjectSeptemberInc/gl-react-native/releases/tag/v2.17.0
