### ISSUE TITLE
App crash on Android 4.1.2

### ISSUE THREAD

**Issue by undef1ned** [ProjectSeptemberInc/gl-react-native#82]
Im running gl-react-native (+gl-react-blur) on HTC Desire 500 with Android 4.1.2 (Adreno 203, GL ES20 supported by HW), the app crashes when the Surface with Blur is rendered, here is the log:

> E/AndroidRuntime(23316): FATAL EXCEPTION: GLThread 2299
> E/AndroidRuntime(23316): java.lang.NoSuchMethodError: android.opengl.GLES20.glGetActiveUniform
> E/AndroidRuntime(23316):  at com.projectseptember.RNGL.GLShader.computeMeta(GLShader.java:152)
> E/AndroidRuntime(23316):  at com.projectseptember.RNGL.GLShader.makeProgram(GLShader.java:183)
> E/AndroidRuntime(23316):  at com.projectseptember.RNGL.GLShader.ensureCompile(GLShader.java:215)
> E/AndroidRuntime(23316):  at com.projectseptember.RNGL.GLCanvas.recSyncData(GLCanvas.java:450)
> E/AndroidRuntime(23316):  at com.projectseptember.RNGL.GLCanvas.syncData(GLCanvas.java:672)
> E/AndroidRuntime(23316):  at com.projectseptember.RNGL.GLCanvas.access$100(GLCanvas.java:49)
> E/AndroidRuntime(23316):  at com.projectseptember.RNGL.GLCanvas$2.run(GLCanvas.java:322)
> E/AndroidRuntime(23316):  at com.projectseptember.RNGL.GLCanvas.runAll(GLCanvas.java:312)
> E/AndroidRuntime(23316):  at com.projectseptember.RNGL.GLCanvas.onDrawFrame(GLCanvas.java:144)
> E/AndroidRuntime(23316):  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
> E/AndroidRuntime(23316):  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by gre** [comment]
mmh weird. Any idea why it says at runtime there is no method `GLES20.glGetActiveUniform` ?

**Comment by undef1ned** [comment]
I'm trying to figure it out, but other methods are not accessible as well. Seems this is the first one called

**Comment by KendraTang** [comment]
+1, Having the same issue reported on crashlytics, but not able to reproduce it.
Device: Samsung GT-I8262
Android version: 4.1.2

**Comment by st0ffern** [comment]
please post the complete Surface code.. in an example git.

**Comment by sahil-innostax** [comment]
Same issue.My code works fine for all android versions except 4.1.2
What is the minimum android version does this support?
i am using this library with image cropper

**Comment by st0ffern** [comment]
versions gl-react-native v2 or v3?
@sksahil030 learn to supply your code, else none will help you out

**Comment by sahil-innostax** [comment]
"gl-react-native": "^2.47.0"

**Comment by st0ffern** [comment]
gl-react-blur version?

**Comment by sahil-innostax** [comment]
2.0.0

**Comment by st0ffern** [comment]
there is your problem!

**Comment by sahil-innostax** [comment]
i am actually using "https://github.com/stoffern/react-native-image-cropper" 
there is no direct dependency for "gl-react-blur" mentioned in my package.json

**Comment by sahil-innostax** [comment]
which version should be ideally used then

**Comment by sahil-innostax** [comment]
@stoffern Can you give any further update on this issue?
