### ISSUE TITLE
Surface cannot rasterize another surface

### ISSUE THREAD

**Issue by miklosme** [ProjectSeptemberInc/gl-react-native#86]
I think a surface cannot resterize another surface. Is it intended or a bug?

Reproduction:
- Run: https://github.com/CAPSLOCKUSER/GLReactSurfaceInSurface
- Result: `Hello` is visible, `World` is not (because word is contained by two surfaces).

Code: https://github.com/CAPSLOCKUSER/GLReactSurfaceInSurface/blob/master/js/App.js

**Comment by gre** [comment]
OpenGL views can't be rasterized. so yeah, it's not supported.

Instead of doing:

``` html
<Surface>
   <...>
     <Surface>
       <A/>
     </Surface>
   </...>
</Surface>
```

you should be doing

``` html
<Surface>
   <...>
     <A/>
   </...>
</Surface>
```

and it would work.
