### ISSUE TITLE
slow and 1-10 fps on loading

### ISSUE THREAD

**Issue by st0ffern** [ProjectSeptemberInc/gl-react-native#88]
Hi,

I have used gl-react-native with custom shades and also gl-react-contrast-saturation-brightness.
If i edit any of the values, the image instantly rerenders with filters, but i have a huge drop in the FPS.

The drop will be there for 10-15 seconds, and this will add up if i do changes before the FPS goes back up. Is this a know issue?

@gre do know what this is?

**Comment by gre** [comment]
Weird.
What props do you use on the Surface?
what resolution is your images? your surface size?
iOS or Android?

**Comment by gre** [comment]
would be great to provide a minimal example that repro this so I can test and investigate more easily.

**Comment by st0ffern** [comment]
@gre Thanks for fast reply.
I have exported all the screens what deals with gl-react and set up an example app.
This does runs fast and without any FPS drop or latency.

Surface settings, Image sizes and running it on Android, are the same.
React Native versions differ, example app uses latest version and the one with latency uses React Native 0.25.1
Could this have something to do with React Native version?

I will test more today, as this can have something to do with alot of frameworks that are included in the main app. (Redux, Relay, FB ++)

**update**
It is not the RN version..

**Comment by gre** [comment]
Maybe worth trying a `systrace` or a chrome profile to investigate where the bottleneck is.

**Comment by st0ffern** [comment]
@gre 
Well in some cases i can get it to run smoothly on a S6 but not Note 4.

I have now tried the clean version of "gl-react-image-effects" on a S4, and there are some big latency.
Should i run smooth on "all devices" or only the most powerful ones?

**Comment by gre** [comment]
I've noticed gl-react-native is a bit slower on Android (I have a nexus 5) than on iOS (tested on iPhone 6).
I don't know if it's gl-react-native implementation or if it's underlying OpenGL API. If it's OpenGL, I'm not sure how we can improve this.
Maybe this is related to the device pixel ratio too?
It would be great to see what is the size of the surfaceview in Android (not the size you give, but the actual pixel size).
maybe worth trying to force the pixelRatio by providing a `scale={1}` on your surface. You can even try value like `scale={0.5}` or 0.25, see if it does anything to perf (I have a small doubt that scale works on Android, it should, but i'm not entirely sure).
It will be lower quality but it's a tradeoff.

**Comment by gre** [comment]
make sure your images are not too big too, image size have impact on GPU perf.

**Comment by st0ffern** [comment]
@gre I am testing the "gl-react-image-effects" repo on a S4 now.
tried to use scale={1} and scale={0.1} exact same result. no difference in the speed.
Please note that on the S4 i have 60UI-FPS and 0-10 on JS-FPS when i use one slider to alter the image.

**Comment by gre** [comment]
> tried to use scale={1} and scale={0.1} exact same result. no difference in the speed.

but did it changes anything on the display? if not, it's likely not supported.

**Comment by gre** [comment]
I tend to think it's a bug related to the slider. Are you using react-native-material-kit ? I remember having these lag issue with it.

**Comment by st0ffern** [comment]
@gre the display is changing when i change the scale so its supported :)
I am also using React Natives Slider ..

look at the repo here: https://github.com/stoffern/glReacNativeTest
Please note that while i continue to use the slider without releasing it the lagg will increase.

**Comment by gre** [comment]
what if [here](https://github.com/stoffern/glReacNativeTest/blob/master/src/Filter.js#L25) you do:

```
<Saturation ...>
  {this.props.image}
</Saturation>
```

?

does this help the perf?

Using `<Image>` will make gl-react-native to re-rasterize the view everytime you re-render, so it's not very performant, while giving the image source directly will make it caching it.
now for implementing the cover mecanism, it can be done in opengl, but needs to use some shader code for this.. later I might try to implement a component that do this.
This makes me think maybe we should have a `gl-react-image` component that have roughtly the same API as the RN image props but implements it in opengl.

**Comment by st0ffern** [comment]
@gre Spot on. That really made a big difference and made it possible to run on older/slower devices aswell.

One last question:
If i run it like this:

```
<Blur>
    <Saturation>
        <HueRotate>
            {this.props.image}
        </HueRotate>
    </Saturation>
</Blur>
```

Will that be the same as running all shaders in one tag (performance wise)?

**Comment by st0ffern** [comment]
Making a `gl-react-image` sounds good :)

**Comment by gre** [comment]
here you go
https://github.com/gre/gl-react-image
http://greweb.me/gl-react-image/

**Comment by st0ffern** [comment]
Resolved! :)
