### ISSUE TITLE
Custom .babelrc error (Cannot use 'in' operator to search for)

### ISSUE THREAD

**Issue by st0ffern** [ProjectSeptemberInc/gl-react-native#90]
Enviroment:
gl-react: 2.2.3
gl-react-native: 2.27.0
react-native: 0.27.2
Using custom .babelrc file with "babel-preset-react-native". (Required if you want to use Relay)

I dont know if this should be addressed under `babel` or `gl-react-native`.
Setting `"passPerPreset": true,` in .babelrc breaks captureFrame().
I have not tested iOS but it gives error on Android.

Error:
`Cannot use 'in' operator to search for 'base64:jpg' in undefined`
The same error applies for the file handler.

**Comment by gre** [comment]
I recently had issues too with Relay config and the recommended config does not seem to work for my code, and not only for gl-react-native.

have you tried to do something like

``` json
{
  "presets": ["react-native"],
  "plugins": [
    "./plugins/babelRelayPlugin"
  ]
}
```

**Can you tell me if this config works for you?** (path may need to be adapted – I had make my **web** project work with this code but I have not tested in React Native (even though i'm using react-native preset for web ^^))

I'm pretty sure the config documented in Relay is somehow wrong... It looks to break some ES2015 feature like the class property method.

Minimum breaking code:

``` js
class A {
  bar () { return "it works!"; }
  foo = () => this.bar();
}
new A().foo();
```

^ that code is valid in React Native default packager config. it is not in Relay passPerPreset config. **`this` is undefined**.

I have tons of these in my codebase, and this config breaks it. So basically I'm pretty sure it's not an issue on gl-react-native but it's something to raise on Relay / React Native.

(feel free to reference my comment)

**Comment by st0ffern** [comment]
Wow, you are awsome!
I can confirm that your babelrc code works :)

**Comment by gre** [comment]
maybe worth informing Relay that their doc is wrong (can't find again where it is!)

**Comment by st0ffern** [comment]
Could this be the it? https://github.com/facebook/relay/issues/935
Think its better if you inform them as i started with ES2015 1 months ago, and are quite new to all this.
