### ISSUE TITLE
providing a texture in a uniform not defined in the shader crashes with cryptic error

### ISSUE THREAD

**Issue by allthetime** [ProjectSeptemberInc/gl-react-native#91]
I'm not sure what I'm doing wrong, but I am attempting to use child nodes via GL.Uniform and keep coming up against this error:

![](http://imgur.com/c2q0BJR.jpg)

This happens if I directly use an image link, or another shader. Here is the simplest code that shows the problem.

```
module.exports = GL.createComponent(
  ({ image, originalImage, children }) =>
  <GL.Node
    shader={shaders.imageBlend}
    uniforms={{ originalImage, image }}
  >
    <GL.Uniform name='bg'>
      http://imgur.com/c2q0BJR.jpg
    </GL.Uniform>
  </GL.Node>,
  { displayName: "HelloGL" });
```

**Comment by allthetime** [comment]
btw, I'm simply looking to include a background texture behind my main shader within the same Surface, and not really sure what the right way to do that is.

**Comment by gre** [comment]
looks like it's a bug. 'll have to investigate.
In the meantime, you should be able to do:

``` js
uniforms={{ originalImage, image, bg: "http://imgur.com/c2q0BJR.jpg" }}
```

for your usecase I see 2 ways:
- use backgroundColor="transparent" on the Surface and play with absolute positionning to put the Image in background (or maybe just with `<Image> <Surface backgroundColor="transparent" .../> </Image>` (I think it's a possible way to impl background image in RN).
- do your current approach using a shader. If you want to do a screenshot via gl-react-native and you want the background to be on that screenshot, you will need to take this approach.

**Comment by gre** [comment]
also, the first option is not possible in Android because #72

**Comment by allthetime** [comment]
Using `uniforms={{ originalImage, image, bg: "http://imgur.com/c2q0BJR.jpg" }}` or my current approach using a shader gives the same error. It also crashes Android, but I don't have detailed feedback available at the moment. I've seen some examples around that use this format so I'm surprised that it's not working. 
Are you saying that this should be working?

```
module.exports = GL.createComponent(
  ({ image, originalImage, children }) =>
  <GL.Node
    shader={shaders.imageBlend}
    uniforms={{ originalImage, image, 'bg': "http://imgur.com/c2q0BJR.jpg" }}
  >
  </GL.Node>,
  { displayName: "imageBlend" });
```

because it's not for me. I'm wondering if there might be something wrong with my setup (versions?)

I do need to screen shot the Surface with one shader with an image behind it, so using `<Image>` is not an option.

**Comment by gre** [comment]
i'll try to repro.

can you give me what version of gl-react and gl-react-native you are using?

**Comment by gre** [comment]
also, can you tell me how you use the ImageBlend component, what are the props?

**Comment by allthetime** [comment]
ImageBlend is simple, it just needs to have an image link given to it. (In my case its an image from a camera, but here is a simple example. It is currently broken, but if you take out the `GL.Uniform` it will work.

https://gist.github.com/allthetime/a64a2a4efc4dc0d1a4c4aa14a0fdf0cc

gl-react@2.2.4
gl-react-native@2.27.0

I have found a way to implement a background image in GLSL in a single shader for now, but let me know if I can help you in any way to figure this out.

**Comment by allthetime** [comment]
Something I've noticed:

I had another image prop being passed into ImageBlend. If I did not explicitly use it in the GLSL code (defined the uniform variable but didn't actually use the variable), the same error would be thrown (the one I screenshotted in my first post, dictionary cannot be converted to array)

**Comment by gre** [comment]
you are not using bg in your shader. It's not even defined as a uniform.
I was able to repro the error you have. but as soon as I define it and use it, the error is gone.

The error is still weird, it's something to improve in our logs.

**Comment by gre** [comment]
In our implementation I should fix that uniforms should just be ignored if they do not exists.
In the meantime you will have to define the uniform AND use it or not passing it to uniforms props.
If you don't use it in your glsl you also get the error because for OpenGL it's like if you had not defined it: looks like OpenGL is doing some simplification and drops unused uniforms.

**Comment by allthetime** [comment]
hmm, I see! thanks for the help.

I guess my last question is, if you don't mind, how can I combine two completely different shaders/shader components in a single Surface?

**Comment by gre** [comment]
@allthetime via texture too.

e.g. technically this work:

``` html
<ImageBlend originalImage={
  <ImageBlend originalImage={
    <ImageBlend originalImage={'https://www.newton.ac.uk/files/covers/968361.jpg'} />
  } />
} />
```

see https://projectseptemberinc.gitbooks.io/gl-react/content/docs/api/createComponent.html#composing-effects

**Comment by allthetime** [comment]
@gre thank you so much for your help. Let me know if I am getting annoying in the issues, but I will probably post a bit over the next few days when I come across oddities. I didn't really understand what was going on with GLSL before but I'm starting to get it, so I'll do my best to only bother you with platform specific issues.

I'm in a huge crunch right now, but I'm really interested in this project and will probably dive into the codebase to both learn and contribute in the coming months.

**Comment by gre** [comment]
@allthetime sure, no worries!

Happy GL :)
