### ISSUE TITLE
Exception when setting more than one uniform in a shader

### ISSUE THREAD

**Issue by joewood** [ProjectSeptemberInc/gl-react-native#97]
I'm using `gl-react-native` version 2.28.3 on React Native 0.29 (and tested on 0.28). 
I'm running this on Android 4.4.2 on the regular emulator.

I can run the "Hello World" sample fine on the emulator. However, when I set more than one value in `uniforms` the application fails with the following:

```
W/dalvikvm( 4847): threadid=16: thread exiting with uncaught exception (group=0xb0d0ab20)
E/AndroidRuntime( 4847): FATAL EXCEPTION: GLThread 219
E/AndroidRuntime( 4847): Process: com.kiosk, PID: 4847
E/AndroidRuntime( 4847): java.lang.NullPointerException
E/AndroidRuntime( 4847):        at com.projectseptember.RNGL.GLCanvas.recSyncData(GLCanvas.java:479)
E/AndroidRuntime( 4847):        at com.projectseptember.RNGL.GLCanvas.recSyncData(GLCanvas.java:466)
E/AndroidRuntime( 4847):        at com.projectseptember.RNGL.GLCanvas.syncData(GLCanvas.java:762)
E/AndroidRuntime( 4847):        at com.projectseptember.RNGL.GLCanvas.access$100(GLCanvas.java:49)
E/AndroidRuntime( 4847):        at com.projectseptember.RNGL.GLCanvas$2.run(GLCanvas.java:322)
E/AndroidRuntime( 4847):        at com.projectseptember.RNGL.GLCanvas.runAll(GLCanvas.java:312)
E/AndroidRuntime( 4847):        at com.projectseptember.RNGL.GLCanvas.onDrawFrame(GLCanvas.java:144)
E/AndroidRuntime( 4847):        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
E/AndroidRuntime( 4847):        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
W/ActivityManager( 1269):   Force finishing activity com.kiosk/.MainActivity
```

This seems to be consistently failing whenever there is more than one uniform (of the same type). A single uniform works fine.

The repro code is below, with a slightly modified hello-world component. The code below fails. If you edit the code and remove the `p2` from the `uniforms` property (without touching the fragment) it works fine.

``` javascript
const GL = require("gl-react");
const React = require("react");
const {Surface} = require("gl-react-native");

const shaders = GL.Shaders.create({
  helloGL: {
    frag: `
precision highp float;
// added two uniforms
uniform float p1;
uniform float p2;

varying vec2 uv; 

void main () { // This function is called FOR EACH PIXEL
  gl_FragColor = vec4(uv.x, uv.y, p1, 1.0); 
}
    `
  }
});

const HelloGL = GL.createComponent(
  () => <GL.Node shader={shaders.helloGL} uniforms={{ p1: 10.0, p2:11.0 }} />,
  { displayName: "HelloGL" });


export default () => <Surface width={300} height={200}>
  <HelloGL />
</Surface>
```

**Comment by gre** [comment]
in your GLSL, you are not using `uniform float p2;`, the OpenGL implementation when compiling this will remove it, so when we ask to OpenGL to retrieve the list of uniforms we will only see and get `p1`.

`p2` does not exist from OpenGL perspective.

i've created https://github.com/ProjectSeptemberInc/gl-react-native/issues/98 to make Android logs better, because it should say it more explicitly, don't know what it breaks with that NPE !
I hope it's not another weird bug.

**Comment by joewood** [comment]
Great, thanks @gre. Strange, sure this used to work :-). 
The uniform removal code seems very thorough, you seem to have to actually use it in an output (and not some dummy intermediate variable). 

Would be great to have a more meaningful exception. Stumped me for a few hours.

**Comment by gre** [comment]
definitely. that's why I created #98.
