### ISSUE TITLE
Suggestion - add some default uniforms for native only animations

### ISSUE THREAD

**Issue by joewood** [ProjectSeptemberInc/gl-react-native#99]
I'm running some time based animations in a shader. I was looking through the code and noticed the support for `autoRedraw` on the `Surface`. 

I was wondering, if the **gl-react-native** added a set of uniforms on the native side of the library by default (like `iGlobalFrame` and `iGlobalTime` - like [shadertoy](https://www.shadertoy.com/howto)), then I could avoid `requestAnimationFrame` and just use an `autoRedraw` surface. The animation could run entirely on the native side and avoid adding any traffic to the bridge and any react-native render.

**Comment by gre** [comment]
yeah. That's a good idea.
I would like to keep this "explicitely" set by the user so there is no magic. What I mean is that I think we should have a special flag/symbol that you can set to a uniform that would tell gl-react-native he have to hook this uniform to whatever global info (time / frame).

`<GL.Node uniforms={{ iGlobalFrame: GL.UniformFrame, iGlobalTime: GL.UniformTime }} />`

it's also compatible with my idea in https://github.com/ProjectSeptemberInc/gl-react/issues/27 to have a `GL.PreviousBuffer` symbol that would allow to pass-in backbuffer.

**Comment by joewood** [comment]
Yeah, that's much better. Easier to call the uniform what you like too.

**Comment by gre** [comment]
I'll try to address this soon. My ultimate goal is to make gl-react enough feature complete so you can implement a ShaderToy example. ;)

**Comment by joewood** [comment]
Yes, that would be great. Not far off already.
